### ISSUE TITLE
Enabling lazy loading did not achieve the desired effect

### ISSUE THREAD

**Issue by youngledo** [mybatis/spring-boot-starter#1041]
Using the example code of this project, I enabled lazy loading, but found that it still loaded when starting.

<img width="1377" alt="image" src="https://github.com/user-attachments/assets/431ae0a8-be28-4099-9160-2269e568d211" />

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/a2b041d7-4897-4183-89fe-ddbc999f5628" />

My understanding is that when lazy loading is enabled, the following code will not execute without being called:
<img width="1256" alt="image" src="https://github.com/user-attachments/assets/0fe332cf-48ba-4f5a-88d1-3aa4ed32c64d" />

Here is my simplified code based on the example:
```java
package sample.mybatis.xml;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SampleXmlApplication {

  public static void main(String[] args) {
    SpringApplication springApplication = new SpringApplication(SampleXmlApplication.class);
    springApplication.run(args);
  }

}
```
Other code has not been actively triggered or called:
<img width="356" alt="image" src="https://github.com/user-attachments/assets/30ee5e75-594a-4225-a37d-acf4b2e7a09a" />

**Comment by youngledo** [comment]
However, it seems to work when I use '@ MapperScan':
<img width="934" alt="image" src="https://github.com/user-attachments/assets/a17fb3b4-1f39-4cc8-9855-23c5fb8bc48f" />

**Comment by youngledo** [comment]
I seem to understand that the `mybatis.configuration.lazy-loading-enabled` is not used to control the lazy loading of Mapper, but to control the lazy loading of SQL scripts, right?

**Comment by harawata** [comment]
Hello @youngledo ,

Yes, in MyBatis, lazy loading means lazily executing nested SELECTs.
https://mybatis.org/mybatis-3/sqlmap-xml.html#nested-select-for-association

**Comment by youngledo** [comment]
OK, but I have a question, why does the configuration not provide lazy loading of Bean, but through "@ MapperScan?

`mybatis.lazy initialization=true` is invalid.

**Comment by harawata** [comment]
- Lazy loading is a feature of [MyBatis](https://mybatis.org/mybatis-3/) (we call it "the core").
- Lazy initialization is a feature of Spring.

These two are completely different and unrelated.
And [`@MapperScan`](https://mybatis.org/spring/mappers.html#scanning-for-mappers) is an annotation provided by [MyBatis Spring](https://mybatis.org/spring/).

**Comment by youngledo** [comment]
Okay, but I still want to ask if there will be a file configuration corresponding to `@ MapperScan(lazyInitialization = "true")` provided? For example:
```
mybatis.lazy-initialization=true
```

**Comment by harawata** [comment]
I don't think there is such a plan.

Please explain why you cannot use `@MapperScan(lazyInitialization = true)`.

**Comment by youngledo** [comment]
In some cases, `@MapperScan` may not be required, but a configuration file may be required. Of course, this may not be important.
