### ISSUE TITLE
How can i set validation-query and test-on-borrow properties to my datasource ?

### ISSUE THREAD

**Issue by thiaguel** [mybatis/spring-boot-starter#105]
I use mybatis with Teradata as Database.  Every night, Teradata kill all idle connections from my pool.
That occurs exception when my application tries to connect to the database, because all connections have been killed. I tried to set theses properties 
spring:
  datasource:
    validation-query: select 1
    test-on-borrow: true .
But Mybatis seems to ignore it.
Can you help me solving this problem ?

**Comment by kazuki43zoo** [comment]
@thiaguel 

What version of spring-boot is used ? 
1.3.x ? 1.4.0+ ?

Since spring-boot 1.4, property keys to configure connection pool settings has been changed.
For details, please refer to [the Spring Boot 1.4 Release Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4-Release-Notes#datasource-binding).

**Comment by thiaguel** [comment]
Thank you for your response.
i'm using 1.4.0.RELEASE  for spring-boot

**Comment by kazuki43zoo** [comment]
You should be changed property keys !!

**Comment by thiaguel** [comment]
OK, i must use these one
datasource:
 tomcat :   
    validation-query: select 1
    test-on-borrow: true 

Is it right ?

**Comment by kazuki43zoo** [comment]
Please try as follow:
```
spring:
  datasource:
    tomcat:
        validation-query: select 1
        test-on-borrow: true
````

**Comment by thiaguel** [comment]
Ok, thank you so much kazuki43zoo. 
I will let you know tomorrow.

**Comment by kazuki43zoo** [comment]
Hi @thiaguel 
If you cannot resolve this issue, please reopen this.

**Comment by thiaguel** [comment]
Good,  that resolves the issue.
Thank you .

**Comment by rakeshdasari** [comment]
Team, to use this property shall I give in my appliation.properties?
spring.datasource.tomcat.test-on-borrow=true
or
spring.datasource.test-on-borrow=true

will it work if I am not using connection pool?

**Comment by kazuki43zoo** [comment]
> Team, to use this property shall I give in my appliation.properties?

Yes. 
Note: The property key is different depending on spring-boot version or connection pool library.

> will it work if I am not using connection pool?

Sorry, I can not understand intention of your question :(
