### ISSUE TITLE
Compatibility issue with spring boot 1.4.x

### ISSUE THREAD

**Issue by zxkane** [mybatis/spring-boot-starter#108]
Everything works fine when using mybatis-spring-boot-starter 1.1.1 and spring boot 1.3.8. Even upgrading mybatis lib to latest 3.4.1.

After upgrading spring boot to 1.4.1, I got below exception when launching my app,

> Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'URL [jar:file:build/libs/hezhibo-backend-1.0.0.jar!/BOOT-INF/classes/com/cn/zbb/mapping/DmClassInfoMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: java.lang.IllegalArgumentException: Result Maps collection already contains value for com.cn.zbb.dao.DmClassInfoDao.mapper_resultMap[BaseResultMap]_collection[teacher]
>   at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:522)
>   at org.mybatis.spring.SqlSessionFactoryBean.afterPropertiesSet(SqlSessionFactoryBean.java:381)
>   at org.mybatis.spring.SqlSessionFactoryBean.getObject(SqlSessionFactoryBean.java:546)
>   at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration.sqlSessionFactory(MybatisAutoConfiguration.java:130)
>   at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52861ccb.CGLIB$sqlSessionFactory$0(<generated>)
>   at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52861ccb$$FastClassBySpringCGLIB$$821313a.invoke(<generated>)
>   at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
>   at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
>   at org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$52861ccb.sqlSessionFactory(<generated>)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:498)
>   at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
>   ... 67 common frames omitted
> Caused by: org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: java.lang.IllegalArgumentException: Result Maps collection already contains value for com.cn.zbb.dao.DmClassInfoDao.mapper_resultMap[BaseResultMap]_collection[teacher]
>   at org.apache.ibatis.builder.xml.XMLMapperBuilder.configurationElement(XMLMapperBuilder.java:120)
>   at org.apache.ibatis.builder.xml.XMLMapperBuilder.parse(XMLMapperBuilder.java:92)
>   at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:520)
>   ... 80 common frames omitted
> Caused by: java.lang.IllegalArgumentException: Result Maps collection already contains value for com.cn.zbb.dao.DmClassInfoDao.mapper_resultMap[BaseResultMap]_collection[teacher]
>   at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:837)
>   at org.apache.ibatis.session.Configuration$StrictMap.put(Configuration.java:809)
>   at org.apache.ibatis.session.Configuration.addResultMap(Configuration.java:591)
>   at org.apache.ibatis.builder.MapperBuilderAssistant.addResultMap(MapperBuilderAssistant.java:214) 

The mapper xml looks like below,

```
<mapper namespace="com.cn.zbb.dao.DmClassInfoDao" >
  <resultMap id="BaseResultMap" type="com.cn.zbb.model.DmClassInfo" >
    <id column="DMCI_ID" property="dmciId" jdbcType="INTEGER" />
    <result column="DMCI_Class_Name" property="dmciClassName" jdbcType="VARCHAR" />
    <result column="DMCI_Teacher_ID" property="dmciTeacherId" jdbcType="INTEGER" />
    <result column="DMCI_Remark" property="dmciRemark" jdbcType="VARCHAR" />
    <result column="DMCI_School_ID" property="dmciSchoolId" jdbcType="INTEGER" />
    <result column="DMCI_Grade_Name" property="dmciGradeName" jdbcType="VARCHAR" />
    <result column="DMCI_Grade_Type" property="dmciGradeType" jdbcType="VARCHAR" />
    <result column="DMCI_Update_Time" property="dmciUpdateTime" jdbcType="TIMESTAMP" />
    <result column="DMCI_GUID" property="dmciGuid" jdbcType="VARCHAR" />
    <collection property="teacher" ofType="com.cn.zbb.model.DmTeacherInfo">
        <id column="DMTI_ID" property="dmtiId" jdbcType="INTEGER" />
        <result column="DMTI_Teacher_Name" property="dmtiTeacherName" jdbcType="VARCHAR" />
        <result column="DMTI_Sex" property="dmtiSex" jdbcType="VARCHAR" />
        <result column="DMTI_ID_Number" property="dmtiIdNumber" jdbcType="VARCHAR" />
        <result column="DMTI_Home_Address" property="dmtiHomeAddress" jdbcType="VARCHAR" />
        <result column="DMTI_Telephone" property="dmtiTelephone" jdbcType="VARCHAR" />
        <result column="DMTI_Mailbox" property="dmtiMailbox" jdbcType="VARCHAR" />
        <result column="DMTI_Education" property="dmtiEducation" jdbcType="VARCHAR" />
        <result column="DMTI_QQ" property="dmtiQq" jdbcType="VARCHAR" />
        <result column="DMTI_State" property="dmtiState" jdbcType="VARCHAR" />
        <result column="DMTI_School_ID" property="dmtiSchoolId" jdbcType="INTEGER" />
        <result column="DMTI_Update_Time" property="dmtiUpdateTime" jdbcType="TIMESTAMP" />
        <result column="DMTI_GUID" property="dmtiGuid" jdbcType="VARCHAR" />
    </collection>
  </resultMap>
```

Any suggestion?

**Comment by kazuki43zoo** [comment]
Hi @zxkane, can you provide a repro project on GitHub ? I want to confirm configurations in your application.

Thanks.

**Comment by zxkane** [comment]
Thanks for quick response.

You can play it with the test repo(
https://github.com/zxkane/mybatis-spring-boot-test).

I also observe something else strange. The app can be launched well in
IDE(IntelliJ IDEA). But it would fail to be launched after packing it as
fat jar.

```bash
./gradlew clean build
java -jar build/libs/mybatis-spring-boot-test-1.0.0.jar
```


Kane

https://vme360.com

**Comment by kazuki43zoo** [comment]
Hi @zxkane ,
Probably, this issue is problem of the Spring Boot 1.4 (or/and Spring Framework 4.3). I found a related issue on Spring Framework JIRA ticket ([SPR-13685](https://jira.spring.io/browse/SPR-13685)) .

I will suggest to use mapper file auto loading feature instead of. (this solution is recommended)

* delete the `mapperLocations` property.

  ```diff
  mybatis:
    typeAliasesPackage: com.cn.zbb.model
  -  mapperLocations: classpath*:**/dao/*.xml
  ```

* change storing directory and file name of mapper file as follow:

  ```diff
  .
  └── src
      └── main
          ├── java
          │   └── com
          │       └── cn
          │           └── zbb
          │               ├── MybatisSpringBootApp.java
          │               ├── controller
          │               ├── dao
          │               │   ├── DmClassInfoDao.java
          │               │   └── DmTeacherInfoDao.java
          │               ├── model
          │               └── service
          └── resources
              └── com
                  └── cn
                      └── zbb
  -                        └── mapper
  +                        └── dao
  -                            ├── DmClassInfoMapper.xml
  +                            ├── DmClassInfoDao.xml
  -                            └── DmTeacherInfoMapper.xml
  +                            └── DmTeacherInfoDao.xml
  ```

And you can use the `@Mapper` instead of the `@MapperScan`.

* Add the `@org.apache.ibatis.annotations.Mapper` interface on mapper interfaces as follow:

  ```diff
  + @Mapper
  public interface DmClassInfoDao {
      // ...
  }
  ```

* Delete the `@MapperScan` from java config

  ```diff
  @SpringBootApplication
  @ComponentScan(basePackages = {"com.cn.zbb"})
  - @MapperScan("com.cn.zbb.dao")
  public class MybatisSpringBootApp {
      // ...
  }
  ```

Thanks.

**Comment by zxkane** [comment]
Kazuki, thank you for having look at this issue deeply.

You recommendation is really good. After making those changes, the project
can be launched with spring boot 1.4.1.

Looks like something is broken in spring mvc, pls free to close this issue.


Kane

https://vme360.com

**Comment by kazuki43zoo** [comment]
Hi guys, there are bug that provides duplicate resources form the `PathMatchingResourcePatternResolver` since Spring Boot 1.4(Spring 4.3). For example, path pattern such as `classpath*:/**/mappers/**/*.Mapper.xml` does not work on Spring Boot 1.4.  
This is a regression introduced by [SPR-13685](https://jira.spring.io/browse/SPR-13685). For details refer to the [SPR-14934](https://jira.spring.io/browse/SPR-14934).

Probably, this issue will fix since Spring Boot 1.4.3(Spring 4.3.5).

**Comment by kazuki43zoo** [comment]
see https://github.com/spring-projects/spring-boot/issues/7449.

**Comment by kazuki43zoo** [comment]
spring-projects/spring-boot#7449 has been resolved. (However, it has not been release yet)

**Comment by kazuki43zoo** [comment]
I will update to Spring Boot 1.4.3.RELEASE.
