### ISSUE TITLE
Update to Spring Boot 1.5

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#129]
Update to the Spring Boot 1.5

**Comment by kazuki43zoo** [comment]
The build is successful on Travis CI.
See https://travis-ci.org/kazuki43zoo/mybatis-spring-boot/builds/189724545.

**Comment by kazuki43zoo** [comment]
The build is successful on Travis CI using Spring Boot 1.5.1.RELEASE.
See https://travis-ci.org/kazuki43zoo/mybatis-spring-boot/builds/198104373.

**Comment by kazuki43zoo** [comment]
The build is successful on Travis CI using Spring Boot 1.5.2.RELEASE.
See https://travis-ci.org/kazuki43zoo/mybatis-spring-boot/builds/207443918.

**Comment by eddumelendez** [comment]
@kazuki43zoo I would like to release `1.2.1` this week with the addition to `MybatisTest` annotation, then upgrade to `1.3.0` to be fully compatible with spring boot `1.5.x`. WDYT?

**Comment by kazuki43zoo** [comment]
@eddumelendez My oponion is same with you !!

**Comment by kazuki43zoo** [comment]
I've added new milestone(1.3.0) and included this.

**Comment by get2parag** [comment]
I also tried with sprint boot 1.5.2.RELEASE and maybatis-started-1.2.0 works fine. 

Are we adding any new functionality with 1.3.0 milestone?

**Comment by kazuki43zoo** [comment]
> I also tried with sprint boot 1.5.2.RELEASE and maybatis-started-1.2.0 works fine.

Yes, 1.2.0 work fine on Spring Boot 1.5.

> Are we adding any new functionality with 1.3.0 milestone?

We will plan to support `@MybatisTest` similar to `@DataJpaTest` at version 1.2.1.
And ... by 1.3.0, we will plan to support the `excludeAutoConfiguration` attribute added by Spring Boot 1.5 at `@MybatisTest`.
Thanks.
