### ISSUE TITLE
type-handlers-package can't work with `*`?

### ISSUE THREAD

**Issue by Dreampie** [mybatis/spring-boot-starter#131]
successed:
```yml
mybatis:
    type-handlers-package: com.meituan.funds.common.handlers
```

failed:
```yml
mybatis:
    type-handlers-package: com.meituan.funds.**.handlers
```

**Comment by kazuki43zoo** [comment]
Hi @Dreampie , The MyBatis and MyBatis-Spring does not support wildcard.
If you want to support this feature, please create a new issue to the MyBatis or MyBatis-Spring.

Thanks.
