### ISSUE TITLE
multi type-aliases-package

### ISSUE THREAD

**Issue by jlkm2010** [mybatis/spring-boot-starter#135]
Can support config multi type-aliases-package?
It is necessary.
thinks!

**Comment by kazuki43zoo** [comment]
You can use `,` , `;`, ` `, `\t`(tab), `\n`(line feed) as separator character.

**Comment by kazuki43zoo** [comment]
If it does not work, please reopen this.

**Comment by kazuki43zoo** [comment]
I've update the reference document via 3d6caa614e8493d6642c04b74c8a049de1bf9108.

**Comment by L-EMO-N** [comment]
if i wanna use an ant style. what shou i do
