### ISSUE TITLE
how to enable auto-commit ?

### ISSUE THREAD

**Issue by yongdi** [mybatis/spring-boot-starter#140]
I use mybatis-spring-boot-starter and MySQL, everything run ok. but I found that the default configuration is no auto-commit. How to enable it ?

my application.properties:

```properties
spring.datasource.url=jdbc:mysql://...
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.username=...
spring.datasource.password=...

# mybatis
mybatis.type-aliases-package=...
mybatis.mapper-locations=classpath:mapper/*.xml
```

**Comment by kazuki43zoo** [comment]
Please see

* http://docs.spring.io/spring-boot/docs/1.5.1.RELEASE/reference/htmlsingle/#boot-features-connect-to-production-database
* https://tomcat.apache.org/tomcat-8.5-doc/jdbc-pool.html#Common_Attributes

Probably, you can resolve this by following configuration:

```properties
spring.datasource.tomcat.default-auto-commit=true
```

I hope to read a spring boot documentation before question.

Thanks.
