### ISSUE TITLE
about config enum type handler

### ISSUE THREAD

**Issue by jlkm2010** [mybatis/spring-boot-starter#150]
- could support batch config enum type handler?
- such as:  scan all enums， then use a general enum type handler
- this question bothers me for a long time. has not found a good solution
- thanks for your time!

**Comment by kazuki43zoo** [comment]
Sorry, I couldn't understand your question. Could you provide a concrete example for this issue ?

**Comment by jlkm2010** [comment]
- Sorry, this is maybe our Business needs or problem.
- We have a custom parent enum and 100+ sub enums. also have a custom enumtypehandler for them. We want to auto and batch config this enumtypehandler.
- My english is not very well. Very sorry.
- thanks.

**Comment by kazuki43zoo** [comment]
Can not be enough by package scan?

e.g.)
```properties
mybatis.type-handlers-package=com.example.typehandlers
```

**Comment by harawata** [comment]
I think there is only one custom type handler for many enum implementations.
It has been requested several times.
I will reconsider implementing it as a core feature.

**Comment by jlkm2010** [comment]
if can  scan all enum and auto config it with my custom general enumtypehandler ?
Maybe I should solve the problem myself.  This question is very special. Thanks!

**Comment by jlkm2010** [comment]
@harawata You're right, This feature is important to me. Thanks!

**Comment by kazuki43zoo** [comment]
> I think there is only one custom type handler for many enum implementations.

Thanks @harawata !
Probably, I understand this.

**Comment by kazuki43zoo** [comment]
Hi @jlkm2010, 
I've closed this because this feature request seems belong the MyBatis core.
Please move this issue to the MyBatis core.

Thanks for your contribution.

**Comment by kazuki43zoo** [comment]
See https://github.com/mybatis/mybatis-3/pull/947#event-1001495489
