### ISSUE TITLE
How to use the Java configuration bulk insert

### ISSUE THREAD

**Issue by xuyansong1991** [mybatis/spring-boot-starter#151]
How to use the Java configuration bulk insert：

single insert:
  @Insert("INSERT INTO users(userName,passWord,user_sex) VALUES(#{userName}, #{passWord}, #{userSex})")
    void insert(UserEntity user);
bulk insert: 
???

**Comment by eddumelendez** [comment]
@xuyansong1991 this is not the right place for questions you can use stackoverflow with `mybatis` tag.
