### ISSUE TITLE
MybatisAutoConfiguration can't scan the outside package of  the class annotationed by @SpringBootApplication

### ISSUE THREAD

**Issue by ylyxf** [mybatis/spring-boot-starter#153]
I have three classes ,the App can only find Mapper where his self package .
MybatisAutoConfiguration's  line 179:
`AutoConfigurationPackages.get(this.beanFactory)` only return the package where the App is .
when run the App,it tell's me  : 

> Field netTestMapper in com.test.mapper.App required a bean of type 'net.test.mapper.NetTestMapper' that could not be found.
>Action:
>Consider defining a bean of type 'net.test.mapper.NetTestMapper' in your configuration.

com.test.mapper.ComTestMapper:

<pre><code>package com.test.mapper;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ComTestMapper {

}</code></pre>

**net**.test.mapper.NetTestMapper:

<pre><code>
package net.test.mapper;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface NetTestMapper {

}
</code></pre>

com.test.mapper.App: 

<pre><code>package com.test.mapper;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.stereotype.Service;
import net.test.mapper.NetTestMapper;

@SpringBootApplication(scanBasePackages={"net.test","com.test"})
@Service
public class App {

	@Autowired
	ComTestMapper comTestMapper;

	@Autowired
	NetTestMapper netTestMapper;

	public static void main(String[] args) throws Exception {
		SpringApplication.run(App.class, args);
	}
}
</code></pre>
 [test.zip](https://github.com/mybatis/spring-boot-starter/files/883215/test.zip)

**Comment by kazuki43zoo** [comment]
I think this behavior is working as design. If you want to scan mappers that belong outside packages of spring boot application, you can use the `@MapperScan`.

**Comment by kazuki43zoo** [comment]
I've closed because no feedback. If you can reopen always.

**Comment by ppzzyy11** [comment]
> I think this behavior is working as design. If you want to scan mappers that belong outside packages of spring boot application, you can use the `@MapperScan`.
> 
> ```java
> @SpringBootApplication(scanBasePackages={"net.test","com.test"})
> @MapperScan(basePackages = {"net.test","com.test"}, annotationClass = Mapper.class)
> @Service
> public class App {
>     // ...
> }
> ```

works in my situation.
I meet the same problem in my project where I try to @Autowired a mapper from another model.
The annotation in @SpringBootApplication(scanBasePackage) does not work. Here is my project directory.
.
├── HELP.md
├── model
│   ├── model.iml
│   ├── pom.xml
│   └── src
│       └── main
│           └── java
│               └── com
│                   └── example
│                       └── mvcdemo
│                           └── mybatis
│                               ├── config
│                               │   └── MybatisDemoConfig.java
│                               ├── entity
│                               │   └── MybatisDemoUser.java
│                               └── mapper
│                                   └── MybatisDemoUserMapper.java
├── mvnw
├── mvnw.cmd
├── parent-project.iml
├── pom.xml
├── service
│   ├── pom.xml
│   ├── service.iml
│   └── src
│       └── main
│           └── java
│               └── com
│                   └── example
│                       └── mvcdemo
│                           └── GetUserInfo.java
├── start
│   ├── pom.xml
│   ├── src
│   │   └── main
│   │       ├── java
│   │       │   └── com
│   │       │       └── example
│   │       │           └── mvcdemo
│   │       │               └── start
│   │       │                   └── Application.java
│   │       └── resources
│   │           ├── application.properties
│   │           ├── mappers
│   │           │   └── mybatisdemouser-mapper.xml
│   │           ├── static
│   │           │   └── index.html
│   │           └── templates
│   │               └── greeting.html
│   └── start.iml
├── tree
└── web
    ├── pom.xml
    ├── src
    │   └── main
    │       └── java
    │           └── com
    │               └── example
    │                   └── mvcdemo
    │                       └── controller
    │                           └── GreetingController.java
    └── web.iml

38 directories, 24 files
