### ISSUE TITLE
Can not find mapping

### ISSUE THREAD

**Issue by fengzidaikun** [mybatis/spring-boot-starter#155]
I would like to refer to the official example to build a springboot-mybatis project,I joined mybatis-spring-boot-starter to help me configure the basics,But When my code is the same as the official example,My code can not find the mapping

**Comment by fengzidaikun** [comment]
[Uploading springboot-mybatis.ZIP…]()

**Comment by kazuki43zoo** [comment]
@fengzidaikun 
Please post a your question to the [mailing list](https://groups.google.com/forum/#!forum/mybatis-user) or [Stackoverflow](https://stackoverflow.com/questions/ask?tags=mybatis).
A GiHub issue manages only a bug report and a feature request. 

And ... I think  your explanation is not enough. Please provide more detail explanation and simple reproduce project.

Thanks.

**Comment by fengzidaikun** [comment]
[springboot.txt](https://github.com/mybatis/spring-boot-starter/files/907213/springboot.txt)
Please change the suffix to .rar  ,Where the success folder is based on the official example of the reduced project

**Comment by fengzidaikun** [comment]
@kazuki43zoo

**Comment by kazuki43zoo** [comment]
Please move `HotelMapper.xml`  to `src/main/resource/twobug/fiction/mapper` directory as follow:

```
.
├── pom.xml
└── src
　   └── main
　       ├── java
　       │   └── twobug
　       │       └── fiction
　       │           ├── SampleXmlApplication.java
　       │           ├── domain
　       │           │   └── Hotel.java
　       │           └── mapper
　       │               └── HotelMapper.java
　       ├── resources
　       │   ├── application.yml
　       │   └── twobug
　       │       └── fiction
　       │           └── mapper
　       │               └── HotelMapper.xml　// ### Here
　       └── webapp
　           ├── WEB-INF
　           │   └── web.xml
　           └── index.jsp
```

Please post a your question to the [mailing list](https://groups.google.com/forum/#!forum/mybatis-user) or [Stackoverflow](https://stackoverflow.com/questions/ask?tags=mybatis) at next time.

Thanks.
