### ISSUE TITLE
@MyBatisTest does not work

### ISSUE THREAD

**Issue by aisensiy** [mybatis/spring-boot-starter#164]
Use the new `org.mybatis.spring.boot:mybatis-spring-boot-starter-test:1.3.0` but the `@MyBatisTest` annotation does not exists...

```
buildscript {
	ext {
		springBootVersion = '1.5.3.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
	mavenCentral()
}


dependencies {
	compile('org.flywaydb:flyway-core')
	compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.0')
	compile('org.springframework.boot:spring-boot-starter-web')
	runtime('org.springframework.boot:spring-boot-devtools')
	compile('com.h2database:h2:1.4.194')
	compileOnly('org.projectlombok:lombok')
	testCompile('org.mybatis.spring.boot:mybatis-spring-boot-starter-test:1.3.0')
	testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

```java
@RunWith(SpringRunner.class)
@MyBatisTest // <--- not exists!!!!!
@Import(MyBatisUserRepository.class)
public class MyBatisUserRepositoryTest {
    @Autowired
    private UserRepository userRepository;

    @Test
    public void should_create_user_success() throws Exception {
        User user = new User(UUID.randomUUID().toString(), "xushanchuan");
        userRepository.save(user);
        Optional<User> optional = userRepository.findById(user.getId());
        assertThat(optional.get(), is(user));
    }
}

```

**Comment by kazuki43zoo** [comment]
@aisensiy  Could you provide a reproduce project ?
My sample application that build using the Maven is working fine.

**Comment by aisensiy** [comment]
[https://github.com/aisensiy/demo-for-springboot-mybatis](https://github.com/aisensiy/demo-for-springboot-mybatis) I created a new repository for the demo project.

**Comment by kazuki43zoo** [comment]
@aisensiy Thanks for feedback. I will try it at later.

**Comment by kazuki43zoo** [comment]
@aisensiy Is happen this issue in gradle build ? Is it only IDE build ?

**Comment by aisensiy** [comment]
Both, it said 'can not find Symbol `MybatisTest`'. Am I wrong for gradle dependency declare?

**Comment by aisensiy** [comment]
@kazuki43zoo Any idea about that?

**Comment by kazuki43zoo** [comment]
please adding `import org.mybatis.spring.boot.test.autoconfigure.MybatisTest;` .... at `MyBatisRepositoryTest`. and change to `@Import(MyBatisUserRepository.class)` instead of `@Import(UserRepository.class)`.

**Comment by kazuki43zoo** [comment]
@aisensiy

Please post your question to the [mailing list](https://groups.google.com/forum/#!forum/mybatis-user) from next time.

Thanks.
