### ISSUE TITLE
About the mybatis.configuration.map-underscore-to-camel-case

### ISSUE THREAD

**Issue by walkwolf** [mybatis/spring-boot-starter#170]
I use Spring Boot 1.5.3.RELEASE and mybatis/spring-boot-starter 1.3.0 .
Config ```mybatis.configuration.map-underscore-to-camel-case=true``` in my application.properties.
In any case true or false, I get the same result, ineffectively. 
What exactly mean of the ```mybatis.configuration.map-underscore-to-camel-case``` ?

## Mapper
```
@Mapper
public interface TestMapper {
	@Select("select * from access_log order by req_time desc limit 10")
	public List<Map<String, Object>> getLog();
	
	@Select("select * from access_log order by req_time desc limit 10")
	public List<Log> getLog2();
}
```

## Controller
```
@RestController
public class MyController {

	@Autowired
	TestMapper mapper;

	@RequestMapping("/test")
	public List<Map<String, Object>> test() {
		return mapper.getLog();
	}
	
	@RequestMapping("/test2")
	public List<Log> test2() {
		return mapper.getLog2();
	}

}
```
## Log
```
public class Log {
	private String reqTime;
	private String reqIp;
	private String log;

	/**
	 * @return reqTime
	 */
	public String getReqTime() {
		return reqTime;
	}

	/**
	 * @param reqTime
	 */
	public void setReqTime(String reqTime) {
		this.reqTime = reqTime;
	}

	/**
	 * @return reqIp
	 */
	public String getReqIp() {
		return reqIp;
	}

	/**
	 * @param reqIp 
	 */
	public void setReqIp(String reqIp) {
		this.reqIp = reqIp;
	}

	/**
	 * @return log
	 */
	public String getLog() {
		return log;
	}

	/**
	 * @param log
	 */
	public void setLog(String log) {
		this.log = log;
	}

}
```

## Table
```
create table access_log( req_ip varchar(50),req_time timestamp,log varchar(10000));
```

## Output /test
```
[{"req_time":1495524129000,"log":"log..","req_ip":"127.0.0.1"}]
```

## Output /test2
```
[{"reqTime":1495524129000,"log":"log..","reqIp":"127.0.0.1"}]
```

**Comment by kazuki43zoo** [comment]
See explanation of `mapUnderscoreToCamelCase ` in http://www.mybatis.org/mybatis-3/configuration.html.

If you set `mybatis.configuration.map-underscore-to-camel-case=false`,  test2 return response as follow:

```json
[{"reqTime":null,"log":"log..","reqIp":null}]
```

And.. please post a you question to the [mailing list](https://groups.google.com/forum/#!forum/mybatis-user) from next time. We use the GitHub issue to manage bug tracking and feature request.

Thanks.

**Comment by NineSwordsMonster** [comment]
```yaml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
```

Although I set `true`, it is still return `null`

**Comment by kazuki43zoo** [comment]
@NineSwordsMonster 
This issue is already closed. Please create a new issue if there is problem. And I want you to provide a small reproduce project on GitHub.

Thanks.
