### ISSUE TITLE
java config SqlSessionFactoryBean.setTypeHandlersPackage() doesn't work in jar

### ISSUE THREAD

**Issue by PKUliwp** [mybatis/spring-boot-starter#177]
Hi,

I meet a type handler problem when I use java configuration to create a SqlSessionFactory bean. When I use method SqlSessionFactoryBean.setTypeHandlersPackage() to register my handler, my handler doesn't work in my jar(It works in Intellij run). But when I use method register() instead, It backs to normal. I'm sure that I use the right package reference. I think there is something wrong in the method SqlSessionFactoryBean.setTypeHandlersPackage().

My spring boot version is 2.0.0.M2

My code is following:

```
    @Bean(name = "sqlSessionFactory")
    @Autowired
    public SqlSessionFactory sqlSessionFactory(HikariDataSource dataSource,
                                                   org.apache.ibatis.session.Configuration dbConfig) throws Exception{
        System.out.println("sqlSessionFactory is initialized!");
        SqlSessionFactoryBean ssfb = new SqlSessionFactoryBean();
        ssfb.setDataSource(dataSource);
        ssfb.setConfiguration(dbConfig);
        //not work in jar        
        //ssfb.setTypeHandlersPackage(packageRef);
        ssfb.getObject().getConfiguration().getTypeHandlerRegistry().register(EnumUpperUnderscoreTypeHandler.class);
        return ssfb.getObject();
    }
```

**Comment by kazuki43zoo** [comment]
@PKUliwp 

Could you provide a reproduce project on GitHub ?

**Comment by PKUliwp** [comment]
I create a simple project and it has the same problem. You can find it from https://github.com/PKUliwp/mybatis-toy

**Comment by kazuki43zoo** [comment]
@PKUliwp Thank you !!

**Comment by kazuki43zoo** [comment]
You can resolve this issue by adding `SpringBootVFS` as follow:

```diff
@Bean(name = "sqlSessionFactory")
@Autowired
public SqlSessionFactory sqlSessionFactory(DataSource dSource,
                                           org.apache.ibatis.session.Configuration dbConfig) throws Exception{
    SqlSessionFactoryBean ssfb = new SqlSessionFactoryBean();
+    ssfb.setVfs(SpringBootVFS.class);
    ssfb.setDataSource(dSource);
    ssfb.setConfiguration(dbConfig);
    ssfb.setTypeHandlersPackage("com.hulu.pcd.valjoux.handler");
    return ssfb.getObject();
}
```

Note: This issue fixed via #21.

Thanks.

**Comment by PKUliwp** [comment]
It works, thanks!

**Comment by kazuki43zoo** [comment]
Hi @PKUliwp ,

I will advice to use auto-configuration feature provide by mybatis-spring-boot-starter.

Please perform following steps.

1. Remove the `BeanFactory.java`
2. Add the `@org.apache.ibatis.annotations.Mapper` instead of `@Component` on `EntityMapper.java`

```java
package com.hulu.pcd.valjoux.mapper;

import com.hulu.pcd.valjoux.base.Entity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface EntityMapper {
    @Select("select * from entities limit 100")
    List<Entity> selectAllLimit();
}
```
3. Add following properties on `application.properties`.

```properties
mybatis.type-handlers-package=com.hulu.pcd.valjoux.handler
mybatis.configuration.map-underscore-to-camel-case=true
```

You can run the mybatis application on spring-boot!
Let's enjoy using mybatis-spring-boot-starter !!

Thanks.

**Comment by PKUliwp** [comment]
Great! 
I'll try it, thanks!
