### ISSUE TITLE
mybatis mapper scan in springboot 

### ISSUE THREAD

**Issue by yizhiwazi** [mybatis/spring-boot-starter#179]
Hower I can't connect the website .
https://groups.google.com/group/mybatis-user

mybatis mapper scan in springboot only can use @mapperscan in the starter of Application . Or use @Mapper in MapperInterface one by one.

**## How can I specified the location of mapper-interface in springboot application.properties ?**

springboot :
mybatis:
mapper-locations: classpath:mapper/*.xml
mapper-interface-locations: com.hehe.dao # this is not suppoted ..
configuration:
map-underscore-to-camel-case: true

**Comment by kazuki43zoo** [comment]
Currently, you cannot specify mapper locations using `application.properties`. Please use `@MapperScan` if you need to specify mapper localtions.
There is no plan to support definition that used `application.properties` at the moment.

Contributing is welcome !!

Thanks.

**Comment by kazuki43zoo** [comment]
@yizhiwazi I've close this issue. You can reopen this issue always.
