### ISSUE TITLE
import my project has a warning

### ISSUE THREAD

**Issue by wuhongsheng** [mybatis/spring-boot-starter#182]
<img width="1231" alt="2017-08-15 4 42 00" src="https://user-images.githubusercontent.com/10295461/29308525-c759f33e-81d8-11e7-8ab3-a2f58c03aa45.png">

**Comment by kazuki43zoo** [comment]
@wuhongsheng Could you provide more detail information and reproduce project on GitHub ?

I have a one question.
Have you added "Sonatype OSS Snapshots Repository" in your build settings. If you want to a snapshot version, you should add it on your build settings.

See https://github.com/mybatis/mybatis-3/wiki/Maven#snapshot

**Comment by kazuki43zoo** [comment]
Hi @wuhongsheng , Probably this issue can resolve to add a following setting on your `build.gradle`.

```diff
repositories {
    mavenCentral()
    // ...
+    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}
```

**Comment by kazuki43zoo** [comment]
I've closed this issue. If you cannot resolve this issue, please re-open this.
