### ISSUE TITLE
Why config-location does not recognize classpath* configuration?

### ISSUE THREAD

**Issue by j2eegis** [mybatis/spring-boot-starter#186]
I packed the Mapper separately, introduced in the web module, but started the error.

> Caused by: java.io.FileNotFoundException: class path resource [mapper/*.xml] cannot be opened because it does not exist

.
 configuring config-location as classpath*: mapper/*xml

 `mybatis:`
 &nbsp; &nbsp; &nbsp;` config-location:`
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;`classpath*:mapper/*.xml`,
 but not identifying the classpath*, and how to load the XML in the jar package?

**Comment by eddumelendez** [comment]
@j2eegis the right configuration is below

```
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations:classpath:org/mybatis/spring/boot/autoconfigure/repository/CityMapper.xml
```

Seems like you are using the wrong property for mappers.

**Comment by j2eegis** [comment]
@eddumelendez You're right. Thank you very much
