### ISSUE TITLE
Column is null, not return the column

### ISSUE THREAD

**Issue by guoshimeihua** [mybatis/spring-boot-starter#200]
I am querying a list, some columns is null, these columns not return? I have added the setting:

# mybatis setting
mybatis.configuration.cache-enabled=true
mybatis.configuration.jdbc-type-for-null=null
mybatis.configuration.call-setters-on-nulls=true 

the call-setters-on-nulls not work, how to sovle the promble?

**Comment by kazuki43zoo** [comment]
Could you provide more details information and reproduce project(including a test case is good) on GitHub?

**Comment by guoshimeihua** [comment]
thanks, I have solved this problem. this setting is working.

**Comment by doudou06180618** [comment]
How to solve this problem?
