### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by rafaelduqueestrada** [mybatis/spring-boot-starter#204]
I don't use jdk 8 in my project.
When I run the project, the following error happend:

[ERROR] java.lang.UnsupportedClassVersionError: org/mybatis/spring/boot/test/autoconfigure/MybatisTest : Unsupported major.minor version 52.0

I looked in a documentation and didn't see nothing about this version only runs with jdk 8.

I would like to use the MyBatisTest annotation, this annotation will turn my tests easily to do.

Thanks.

**Comment by kazuki43zoo** [comment]
Which version are you using?

```
$ jar xvf mybatis-spring-boot-test-autoconfigure-1.3.1.jar
...
$ javap -v org/mybatis/spring/boot/test/autoconfigure/MybatisTest.class 
Classfile /Users/xxx/Downloads/org/mybatis/spring/boot/test/autoconfigure/MybatisTest.class
  Last modified 2017/08/21; size 1839 bytes
  MD5 checksum 7c606ca11055f2741596d81683ec8fd7
  Compiled from "MybatisTest.java"
public interface org.mybatis.spring.boot.test.autoconfigure.MybatisTest extends java.lang.annotation.Annotation
  minor version: 0
  major version: 50
...
```

If you use 2.0.0-SNAPSHOT, it requires Java 8+.

**Comment by kazuki43zoo** [comment]
1.3.1 supports Java 6+ (java class version: 50).

**Comment by rafaelduqueestrada** [comment]
Thanks guys, 
but unhappily in version 1.3.1 there isn't a MybatisTest.java.

**Comment by kazuki43zoo** [comment]
> but unhappily in version 1.3.1 there isn't a MybatisTest.java.
??

The `@MybatisTest` has been added 1.2.1.
Please confirm again.

**Comment by rafaelduqueestrada** [comment]
Aff, I didn't know that.
Thanks and sorry guys, works with version 1.3.1.
