### ISSUE TITLE
Upgrade to mybatis-spring 2.0 GA

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#206]

**Comment by plavreshin** [comment]
Hi @kazuki43zoo @eddumelendez , 

could you please shed some light on spring boot 2.0 support, as I see you have already commited this
https://github.com/mybatis/spring-boot-starter/commit/8016d04cce4caf27c0b2d9f97c1bbd58e61c3b30 but not yet released. Are there any known caveats?

**Comment by berniegp** [comment]
Spring Boot 2.0 is now released

**Comment by kazuki43zoo** [comment]
We are a discussion about releasing mybatis-spring 2.0 & mybatis-spring-boot 2.0 at now.

Note: I believe the mybatis-spring-boot 1.3.x line work fine on Spring Boot 2.0.

**Comment by berniegp** [comment]
Is this related at all to https://projects.spring.io/spring-data-jdbc ?

I see "Support for MyBatis queries." as a listed feature.

**Comment by raoofm** [comment]
Any timeline for this ?

**Comment by kazuki43zoo** [comment]
The MyBatis-Spring 2.0 will release waiting the MyBatis 3.5.0 GA(release date is undecided yet).
I believe 1.3.x work fine on Spring Boot 2.0.x.
If it does not work fine, please feedback via new issue.

Thanks.

**Comment by kazuki43zoo** [comment]
#12

**Comment by snicoll** [comment]
@kazuki43zoo Do you have a CI build testing the current generation with Spring Boot 2.x? Given it's a major generation, I think that is really necessary. Can you please clarify the timeline? I don't know if https://github.com/spring-projects/spring-boot/issues/14917 is legit but if they are broken use cases, I will have to disable the entry on start.spring.io and remove the starter from the third party reference. 

Let me know, thanks!

**Comment by kazuki43zoo** [comment]
@snicoll I will investigating it and feedback as soon as possible.

**Comment by snicoll** [comment]
@kazuki43zoo Thanks for the feedback. Could you please answer the other questions when you get a min? (CI + timeline)

**Comment by kazuki43zoo** [comment]
@snicoll

> Do you have a CI build testing the current generation with Spring Boot 2.x? Given it's a major generation, I think that is really necessary.

Currently, No. I will add as soon as possible (today or tomorrow).

**Comment by kazuki43zoo** [comment]
@snicoll 

I've created two branches for CI using Spring Boot 2.x.

* [Branch](https://github.com/mybatis/spring-boot-starter/tree/ci-for-1.3.2-on-spring-boot-2.0.x) is based on tag mybatis-spring-boot-1.3.2 and update to spring-boot 2.0.6.RELEASE : https://travis-ci.org/mybatis/spring-boot-starter/builds/445162177

* [Branch](https://github.com/mybatis/spring-boot-starter/tree/ci-for-1.3.2-on-spring-boot-2.1.x) is based on tag mybatis-spring-boot-1.3.2 and update to spring-boot 2.1.0.RC1(Modify some test code) : https://travis-ci.org/mybatis/spring-boot-starter/builds/445212174

All tests are passed.

**Comment by kazuki43zoo** [comment]
@snicoll 

I've created tow branch for CI using mybatis-spring-boot 1.3.2 + Spring Boot 2.x on my sample application.

* [Branch](https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/tree/ci-for-mybatis-spring-boot-1.3.x-on-spring-boot-2.0.x) that use mybatis-spring-boot 1.3.2 + Spring Boot 2.0.6.RELEASE : https://travis-ci.org/kazuki43zoo/mybatis-spring-boot-jpetstore/builds/445260956

* [Branch](https://github.com/kazuki43zoo/mybatis-spring-boot-jpetstore/tree/ci-for-mybatis-spring-boot-1.3.x-on-spring-boot-2.1.x) that use mybatis-spring-boot 1.3.2 + Spring Boot 2.1.0.RC1 : https://travis-ci.org/kazuki43zoo/mybatis-spring-boot-jpetstore/builds/445252636

All integration tests are passed on OpenJDK 8, 10, 11.

**Comment by hazendaz** [comment]
We run the mybatis-spring-boot 1.3.2 with spring boot 2.1.0 and it seems to work just fine.  If I recall, we got some of that moved into production environment a while back.

**Comment by laxika** [comment]
Everything works as expected in my case too. The only problem I see is that I get some warnings on Java 11:

> Loading class 'com.mysql.jdbc.Driver'. This is deprecated. The new driver class is 'com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.apache.ibatis.reflection.Reflector (file:/C:/Users/Laxika/.gradle/caches/modules-2/files-2.1/org.mybatis/mybatis/3.4.5/5200759b13f70652995fd206a52fdc98b01c65cd/mybatis-3.4.5.jar) to method java.lang.Object.finalize()
> WARNING: Please consider reporting this to the maintainers of org.apache.ibatis.reflection.Reflector
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

**Comment by kazuki43zoo** [comment]
@laxika 

Probably it is same issue with https://github.com/mybatis/mybatis-3/issues/1156.
Could you try the mybatis 3.5.0-SNASHOT(mybatis-spring-boot-starter 2.0.0-SNAPSHOT)?

**Comment by snicoll** [comment]
Team, can you share what prevents a release of the starter with official build against Spring Boot 2? It's been a while now and Spring Boot 1 is going to be EOLed next August. Let us know if we can help on the Spring Boot side of things.

**Comment by hazendaz** [comment]
Couple of things we are doing that will affect all mybatis modules being released.

- everything is moving to jdk 8
- our super pom is readying release
- all modules are being upgraded to junit 5
- any other general cleanups with possible introduction of google error prone to make our code better

Generally we dont provide firm dates.  The items above though will be completed before end of January.  Each module runs on their own timelines so not sure when this module will release but it most likely will be after mybatis 3.5.0 and next spring module release.

We will have everything out way before August though.  Other dev's might be able to address a clearer date in regards to this module.  Work is rather active now across the board.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ZJ-Mario** [comment]
666
