### ISSUE TITLE
Enable auto-configure when DataSource is single candidate

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#208]
In the current implementation, an error occurs when defines multiple `DataSource`.
I suggest to change using `@ConditionalOnSingleCandidate` instead of `@ConditionalOnBean`.
This change applied already on auto-configuration classes provided by Spring Boot.

**Comment by h3adache** [comment]
Hey @kazuki43zoo I'm working with a different version of MybatisProperties which allows multiple datasources by default. I think it's feature worth integrating into our project. What do you think? Is there a reason you can think of to not support multiple datasources out of the box?

**Comment by kazuki43zoo** [comment]
Hi @h3adache , Sorry for late replying.

The motivation of this issue is that a behavior matches with the Spring Boot when `DataSource` is not a single candidate. = At first, I will fix an error when defines multiple `DataSource`.

> multiple data sources support 

I think it is good feature!!
I am welcome to your contribution :D

**Comment by kazuki43zoo** [comment]
@h3adache 
I've fixed this. 

> I'm working with a different version of MybatisProperties which allows multiple datasources by default. I think it's feature worth integrating into our project. 

Could you create a new issue for supporting multiple `DataSource`?

**Comment by kazuki43zoo** [comment]
If you want to use the auto-configure feature provided by this project when you register multiple `DataSource` beans, you should indicate the primary `DataSource` bean to be use on auto-configure as follow:

```java
@Bean
@Primary // Add
DataSource dataSource() {
  // ...
  return dataSource;
}
