### ISSUE TITLE
Can we add a parameter for @Mapper to specify the mapping file?

### ISSUE THREAD

**Issue by libbylg** [mybatis/spring-boot-starter#215]
Hi, 

Some times, it is not a good idea to put the sql in the java file.
There is an example:
```java
@Select("select \"DESC\" from T_MYTABLE")
public List<String> getDescs();
```
Did you see the DESC ? I have to escape the  `"` for MySQL, that beacuse the `DESC` is the key word.
So, any place I used the DESC, I have to escaped it . That is why I like put then in the mapping xml files, so I do not need the `\"`.

when I use the mybatis-spring-boot-starter,  it can scan the @Mapper automaticly, but do not support auto load SQL from the file.

so, I hope the mybatis can support this idea.

I hope it working like this:

- MyDao.java
```java
@Mapper(file="classpath*:mybatis/MyDao.mapping.xml")
interface MyDao
{
     List<String> getDescs(String name);
}
```

- mybatis/MyDao.mapping.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper>
    <select id="getDescs"
            parameterType="java.lang.String"
            resultType="java.lang.String" >
        SELECT  "DESC"
        FROM    T_MYTABLE
        WHERE   "NAME" == #{0, jdbcType=VARCHAR}
     </select>
</mapper>
```

Best wishes!

**Comment by kazuki43zoo** [comment]
You can scan a mapper file automatically by saving it in the same package structure as Mapper interface.

e.g.)

Mapper interface : 
src/main/java/com/example/dao/MyDao.java

Mapper xml file :
src/main/resources/com/example/dao/MyDao.xml

Please try it.
Thanks.

**Comment by kazuki43zoo** [comment]
And you can also scan mapper files expressly using `mybatis.mapper-locations` property.

e.g.) application.properties

```properties
mybatis.mapper-locations=classpath*:mybatis/**/*Dao.mapping.xml
```

**Comment by hcxin** [comment]
We can use namespace property in *mapper.xml, like below:

Your mapper interface:
@Mapper
public interface UserMapper {

    User selectUserByName(String name);
}


Your mapper xml file :
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper **namespace="sample.mybatis.mapper.UserMapper"**>
    <select id="selectUserByName" resultType="User">
        select * from user where name = #{name}
    </select>
</mapper>

**Comment by libbylg** [comment]
@kazuki43zoo The 'mybatis.mapper-locations' looks a good idea.

@hcxin I think the mybatis-spring-boot-start do not known where is the mapper xml.

**Comment by libbylg** [comment]
hi,my friends,the 'mybatis.mapper-locations' is working.
Is that means I have to add this line in application.properties? Is there some way to remove it? I think give the user an optional to put the sql in Java file or xml is a good idea :)
Best wishes!

**Comment by libbylg** [comment]
I think the locations of the mapping file is the Java-code but not a configurations which the user can change. So put them in Java file is naturally.

**Comment by kazuki43zoo** [comment]
'mybatis.mapper-locations' is not required.
I've already introduced a solution of rule base scaning a mapper xml file on https://github.com/mybatis/spring-boot-starter/issues/215#issuecomment-357503910  .

You need to specify a same namespace with FQCN of Mapper interface in mapper xml.

e.g.)

```xml
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.example.dao.MyDao">
    <!-- ... -->
</mapper>
```

**Comment by kazuki43zoo** [comment]
Hi @libbylg ,

I've closed this issue because this issue does not belong the mybatis-spring-boot. If you need this feature, I propose to create a new feature request into mybatis core project.

Thanks.
