### ISSUE TITLE
springboot map-underscore-to-camel-case invalid

### ISSUE THREAD

**Issue by hexiaowu** [mybatis/spring-boot-starter#226]
My spring version is 1.5.2, spring-mybatis-start version is 1.3.2,
I set mybatis.configuration.map-underscore-to-camel-case=true in properties.
But the MAP I returned was not converted to Camel named

**Comment by kazuki43zoo** [comment]
Could you provide a reproduce project via GitHub?

**Comment by hexiaowu** [comment]
The problem has been solved. I carefully searched the official documentation and found that mybatis.configuration.map-underscore-to-camel-case=true is working on JavaBeans. It is not on HashMap. I inherited MapWrapper to rewrite the findProperty function. The desired effect
