### ISSUE TITLE
How to user foreach by annotations

### ISSUE THREAD

**Issue by FutureElement** [mybatis/spring-boot-starter#228]
for example, how to write this by annotations @Insert ?
```
<insert id="insert" parameterType="map" >
      insert into label_resources (questionid, labelid)
      values
          <foreach collection="labelid" item="item" index="index" separator=",">
              (#{questionid,jdbcType=BIGINT},#{item})
          </foreach>
</insert>
```

**Comment by kazuki43zoo** [comment]
If you use the `@Insert` annotation, you can specify above sql in `@Insert` as follow:

e.g.)

```java
@Insert(
    "<script>",
    "your insert sql using xml tag(e.g. if, foreach, etc ...)",
    "</script>")
int insert(...);
```

or alternative you can build a dynamic sql using `@InsertProvider` (java code).

e.g.)

```java
@InsertProvider(type=YourSqlProvider.class, method = "buildInsertSql")
int insert(...);
```
```java
public class YourSqlProvider {
    public static String buildInsertSql(Map<String, Object> params) {
        // build an dynamic sql
        return sql;
    }
}
```

or almost you can use BATCH insert provided by JDBC feature via MyBatis.
see https://github.com/mybatis/mybatis-3/wiki/FAQ#how-do-i-code-a-batch-insert.

@FutureElement Please post a question to [the mailing list](https://groups.google.com/forum/#!forum/mybatis-user) from next time. 

Thanks.
