### ISSUE TITLE
remove @AutoConfigureAfter({DataSourceAutoConfiguration.class})

### ISSUE THREAD

**Issue by huayanYu** [mybatis/spring-boot-starter#229]
I think It is not necessary,SqlSessionFactory just need dataSource。

I worte a dynamic-datasource-spring-boot-starter，use this starter,others must exclude  DataSourceAutoConfiguration

```java
@SpringBootApplication(exclude = DataSourceAutoConfiguration.class)
```

The major code llike this！
```java
  @Bean
  public DataSource dynamicDataSource() {
    DynamicRoutingDataSource dynamicRoutingDataSource = new DynamicRoutingDataSource();
    Map<Object, Object> dataSourceMap = new HashMap<>();
    // add Master
    DataSourceProperties masterProperties = properties.getMaster();
    DataSource masterDataSource = createDataSource(masterProperties);
    dataSourceMap.put("master", masterDataSource);
    DynamicDataSourceContextHolder.addDataSourceId("master");
    // add Slaves
    Map<String, DataSourceProperties> slavesProperties = properties.getSlaves();
    slavesProperties.forEach((k, v) -> {
      dataSourceMap.put(k, createDataSource(v));
      DynamicDataSourceContextHolder.addDataSourceId(k);
    });
    dynamicRoutingDataSource.setDefaultTargetDataSource(masterDataSource);
    dynamicRoutingDataSource.setTargetDataSources(dataSourceMap);
    return dynamicRoutingDataSource;
  }
```

Because of @AutoConfigureAfter({DataSourceAutoConfiguration.class})
SqlSessionFactory cant not inject my dynamicDataSource。 
others must manual config SqlSessionFactory and  SqlSessionTemplate。

**Comment by kazuki43zoo** [comment]
@huayanYu 

I will propose adding `@AutoConfigureBefore(DataSourceAutoConfiguration.class)` on your auto-configuration class instead of adding `@SpringBootApplication(exclude = DataSourceAutoConfiguration.class)` on user application.

What do you think?

**Comment by huayanYu** [comment]
@kazuki43zoo  Thank U very much. 
I have finised the starter,but I have not deploy and have no doc。
I will sync to github when i finised doc。
now the project is on china git。
https://gitee.com/baomidou/dynamic-datasource-spring-boot-starter
the demo project is here。 
https://gitee.com/baomidou/dynamic-datasource-example
