### ISSUE TITLE
Where the code can map the results of a database query to the jpa entity

### ISSUE THREAD

**Issue by qwop** [mybatis/spring-boot-starter#246]
Where the code can map the results of a database query to the jpa entity
在哪里代码可以将数据库查询的结果映射到jpa entity

**Comment by qwop** [comment]
@Table
class Person{ 
   private String id;
   private String name;
   private String age;

   @Column(name="p_id")
   public String getId() { return id;}
    @Column(name="p_name")
   public String getName() { return name;}
}




Mapper {
  @Select( 'select * from t_person' )
  Person select();
}

**Comment by kazuki43zoo** [comment]
??? 
The MyBatis does not support JPA annotations.
I cannot understand this issue. Could you explain more?

**Comment by qwop** [comment]
how to support jpa annotations
