### ISSUE TITLE
Sqlsession is not threadsafe,but example in your document use sqlsession as a field,why?

### ISSUE THREAD

**Issue by luzhzhsoft** [mybatis/spring-boot-starter#257]
mybatis document say Sqlsession is not threadsafe and not recommd as field.but in your spring-boot-starter example :

```java
@Component
public class CityDao {

	private final SqlSession sqlSession;

	public CityDao(SqlSession sqlSession) {
		this.sqlSession = sqlSession;
	}

	public City selectCityById(long id) {
		return this.sqlSession.selectOne("selectCityById", id);
	}

}
```

**Comment by kazuki43zoo** [comment]
@luzhzhsoft 

The mybatis-spring-boot is used the `SqlSessionTemplate` provided by mybatis-spring. It is thread safe class.

https://github.com/mybatis/spring-boot-starter/blob/8f7336ff9e5ebd9aa73bc741d6b8380b406139c5/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java#L163-L172

See the javadoc of [`SqlSessionTemplate`](https://github.com/mybatis/spring/blob/ab7ba7e5be3da601b5ab73455f0428e70f1af5b0/src/main/java/org/mybatis/spring/SqlSessionTemplate.java#L58-L60)

**Comment by luzhzhsoft** [comment]
@kazuki43zoo  i got it. SqlSessionTemplate  implents SqlSession .thank u
