### ISSUE TITLE
Why MybatisAutoConfiguration catch ConflictingBeanDefinitionException?

### ISSUE THREAD

**Issue by AngusLean** [mybatis/spring-boot-starter#258]
In class `MybatisAutoConfiguration` line  `ConflictingBeanDefinitionException` 209, the `registerBeanDefinitions` method catch a `IllegalStateException exception`, when a `ConflictingBeanDefinitionException` is happen, usually it's ignored。But in many case, conflict Mapper class is wrong design that should be know in startup time，debug log is weak.

So, should i pull a PR to change this behavior?

**Comment by kazuki43zoo** [comment]
@AngusLean Thanks for your reporting!

I guess it is logic for ignoring an error that occurred by the [`AutoConfigurationPackages#get()`](https://github.com/spring-projects/spring-boot/blob/ce9c053cbfc41f4753830bbb6c55ee7b2487856b/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/AutoConfigurationPackages.java#L76-L77), but I think you opinion are right.
