### ISSUE TITLE
plugins-package option for application.yml

### ISSUE THREAD

**Issue by sathishk** [mybatis/spring-boot-starter#262]
As per the [documentation](http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/)  we shall load type handlers using 

> type-handlers-package: com.xxx.yyy.typehandler

Is there anyway i shall load my plugin classes using application.yml ? something like 

> plugins-package: com.xxx.yyy.mybatis-plugin

**Comment by kazuki43zoo** [comment]
@sathishk 

The mybatis core module does not support to scan plugin classes. Therefore there are no plan to support it in this artifact at now. If you need to it ,please submit new feature request to mybatis core module.

Alternative, I propose to register your plugin classes to DI container using component scan feature provided by Spring core module as follow:

```java
@Component
@Intercepts(...)
public class YourPluginClass implements Interceptor {
  // ...
}
```

The mybatis-spring-boot-autoconfigure provide the feature that detects automatically your plugin beans from DI container(`ApplicationContext`).

**Comment by kazuki43zoo** [comment]
@sathishk Could you provide a feedback? If not feedback, I will close this issue.

**Comment by kazuki43zoo** [comment]
@sathishk 

I've closed this issue because no reply form you.
If there is feedback, please reopen this issue.

Thanks.
