### ISSUE TITLE
分页在@PostConstruct注解下不生效

### ISSUE THREAD

**Issue by HumFei** [mybatis/spring-boot-starter#263]
@PostConstruct
    public void initTest(){
        test1();
        test2();
    }
    private void test1(){
        List<Permission> list = permissionDao.selectAll();
        System.out.println("test1");
        System.out.println(list.size());
    }
    private void test2(){
        PageMethod.startPage(1, 20);
        List<Permission> list = new PageInfo<>(permissionDao.selectAll()).getList();
        System.out.println("test2");
        System.out.println(list.size());
    }

dao:
public interface PermissionDao extends Mapper<Permission> {
}

输出：
test1
55
test2
55

**Comment by kazuki43zoo** [comment]
What is `PageMethod` ?
The MyBatis does not provide `PageMethod` class.
Could you explain more detail and provide small reproduce project via GitHub?

**Comment by HumFei** [comment]
I am so sorry, I misread the title, this should be a problem with com.github.pagehelper.
