### ISSUE TITLE
Spring Boot & mybatis-spring -org.apache.ibatis.type.TypeException: Could not resolve type alias

### ISSUE THREAD

**Issue by gituser786** [mybatis/spring-boot-starter#278]
I am using spring boot 1.5.4 & mybatis-spring 1.3.0 along with mybatis-spring-boot-starter.  Whenever I am running my standalone application via eclipse I am able to run. when I run the executable jar file in command line, I am getting below error.
Error creating bean with name 'classNameMapper' defined in class path resource [mybatis-context.xml]: Cannot resolve reference to bean 'sqlSessionFactory' while setting bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [mybatis-context.xml]: Invocation of init method failed; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'class path resource [com/../..//mapper/MyMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. Cause: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'MyClass'.  Cause: java.lang.ClassNotFoundException: Cannot find class: MyCLass
 	<typeAliases>
		<package name="com.package.name.entity"/>
	</typeAliases> 

Please help me

**Comment by kazuki43zoo** [comment]
@gituser786 @RollsBean @deoxyseia @iver3on

This issue transferred from mybatis/mybatipse project. Could you feedback for this issue? (Could provide a small reproduce project?)
If not feedback, I will close this issue.

**Comment by kazuki43zoo** [comment]
@gituser786 @RollsBean @deoxyseia @iver3on

I've closed this issue because no feedback.
If there is problem, please reopen this.

**Comment by chris-peng-1244** [comment]
I just created a mini project that reproduces a similar issue. Here is the git repo. https://github.com/chris-peng-1244/ibatis-resolve-type-alias

The project works fine in IntelliJ, but if I execute `java -jar xxxx.jar` it complained that BookDO couldn't be resolved.

The reason that this project followed some very unorthorgnal file structures and naming conventions is that:
1. The real project has 4 data sources that need configuration
2. It was developed in Spring 4 originally.
3. I tried to port it to Spring boot 2.1

Hope the demo helps clarify the problems a little better.

**Comment by kazuki43zoo** [comment]
@chris-peng-1244 

Please use the `SpringBootVFS` as follow:

```java
SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
factoryBean.setVfs(SpringBootVFS.class);
// ...
```

**Comment by chris-peng-1244** [comment]
@kazuki43zoo It works, thank you so much!

**Comment by ChiDNMSE60717** [comment]
Thank @chris-peng-1244

**Comment by kazuki43zoo** [comment]
@adrixgc Please see http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Using_the_SpringBootVFS. Is OK?

**Comment by ids1207** [comment]
> @adrixgc Please see http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Using_the_SpringBootVFS. Is OK?

nothing changes.. 
spring boot can not find type alias but complete class name with package..

**Comment by ids1207** [comment]
> > @adrixgc Please see http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Using_the_SpringBootVFS. Is OK?
> 
> nothing changes..
> spring boot can not find type alias but complete class name with package..

oh! it works.
i just put the package location in  setTypeAliasesPackage method,
not just in setTypeAliasesPackage method.

**Comment by xiao-ma-nong** [comment]
已经指定包名，全名称了
为什么还是会报错

`<update id="updateGenTableColumn" parameterType="com.cainaer.gen.domain.GenTableColumn">`

`Caused by: org.apache.ibatis.builder.BuilderException: Error resolving class. Cause: org.apache.ibatis.type.TypeException: Could not resolve type alias 'GenTableColumn'.  Cause: java.lang.ClassNotFoundException: Cannot find class: GenTableColumn`

**Comment by kazuki43zoo** [comment]
@xiao-ma-nong 

This issue is closed already. If you have a problem, please create a new issue with reproduce project via GitHub.
