### ISSUE TITLE
Cannot coexist

### ISSUE THREAD

**Issue by StateGrace** [mybatis/spring-boot-starter#29]
@Bean
    @ConditionalOnMissingBean
    public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
        SqlSessionFactoryBean factory = new SqlSessionFactoryBean();
        factory.setDataSource(dataSource);
        if (StringUtils.hasText(this.properties.getConfig())) {
            factory.setConfigLocation(
                    this.resourceLoader.getResource(this.properties.getConfig()));
        }
        if (StringUtils.hasText(this.properties.getTypeAliasesPackage()))
            factory.setTypeAliasesPackage(this.properties.getTypeAliasesPackage());
        if (StringUtils.hasText(this.properties.getTypeHandlersPackage()))
            factory.setTypeHandlersPackage(this.properties.getTypeHandlersPackage());
        if (this.properties.getMapperLocations()!=null && this.properties.getMapperLocations().length>0)
            factory.setMapperLocations(this.properties.getMapperLocations());
        return factory.getObject();
    }

**Comment by Jaware** [comment]
annotation and xml config file can not exist together,i met this problem too,can anyone fix it ?

**Comment by emacarron** [comment]
Sorry we need some text to understand the issue. Please as for a reopen if needed.
