### ISSUE TITLE
MapperScanQuestion

### ISSUE THREAD

**Issue by biuabiu** [mybatis/spring-boot-starter#296]
I hava Two project, one A ,one B , B  dependency A, i use B server why mapperScan is all A project 
 mapperStatements ? please help me 
![image](https://user-images.githubusercontent.com/38499411/52105589-3fa87f80-262a-11e9-833a-b9d04bc177fd.png)

**Comment by biuabiu** [comment]
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)

**Comment by kazuki43zoo** [comment]
Hi @biuabiu ,

I can not help with just the information currently provided from you.
I would like you to explain in more detail what is the problem. Could you provide informations as follow:

* small reproduce project(Maven or Gradle)
* expected result
* actual result
* etc ...

**Comment by biuabiu** [comment]
@kazuki43zoo 
this is two  maven project;

I expect that when Project A relies on Project B, Project B still scans related statement B, but now when Project A relies on B, Project B scans statement A

**Comment by kazuki43zoo** [comment]
@biuabiu Could you provide small reproduce project via GitHub?

**Comment by biuabiu** [comment]
Okay, I'll submit one tomorrow when I have time-------- 原始邮件 --------主题：Re: [mybatis/spring-boot-starter] MapperScanQuestion (#296)发件人：Kazuki Shimizu 收件人：mybatis/spring-boot-starter 抄送：axxc <545597162@qq.com>,Mention @biuabiu Could you provide small reproduce project via GitHub?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mybatis/spring-boot-starter","title":"mybatis/spring-boot-starter","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mybatis/spring-boot-starter"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kazuki43zoo in #296: @biuabiu Could you provide small reproduce project via GitHub?"}],"action":{"name":"View Issue","url":"https://github.com/mybatis/spring-boot-starter/issues/296#issuecomment-479537457"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mybatis/spring-boot-starter/issues/296#issuecomment-479537457",
"url": "https://github.com/mybatis/spring-boot-starter/issues/296#issuecomment-479537457",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by biuabiu** [comment]
@kazuki43zoo Okay, I'll submit one tomorrow when I have time

**Comment by biuabiu** [comment]
hi @kazuki43zoo   我提交了项目,如果你有时间的话你可以看一下,谢谢
[这是有关我提出的小型项目](https://github.com/biuabiu/mybatis-demo)

**Comment by biuabiu** [comment]
@kazuki43zoo  I submitted the project. If you have time, you can have a look at it. Thank you.

**Comment by kazuki43zoo** [comment]
Hi @biuabiu , Thanks for providing the reproduce project!

Please try as follow:

* demo-A/src/main/resources/application.properties

```diff
-mybatis.mapper-locations=classpath:/mapper/*.xml
+mybatis.mapper-locations=classpath*:/mapper/*.xml
```

If you want to scan mapper xml files from all dependency artifacts, you should specify `classpath*:` prefix instead if `classpath:` prefix. (This is Spring Framework feature)

**Comment by biuabiu** [comment]
@kazuki43zoo   OK, I'll take the time to see it tomorrow. Thank you for checking

**Comment by biuabiu** [comment]
@kazuki43zoo  Thank you. This feature has solved this problem. Thank you again for your help.
