### ISSUE TITLE
There is case that cannot scan classes using SpringBootVFS

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#301]
See https://github.com/mybatis/mybatis-3/issues/1500.

If following all conditions are matched, the `SpringBootVFS` cannot scan classes correctly.

* Run without executable jar(e.g. Maven/Gradle Plugin, IDE, etc...) 
* Scanning target classes are stored in jar file under maven local repository (e.g. `${HOME}/.m2/repository`)
* Specified scanning base package is matched with prefix of groupId

In this case, all conditions are matched as follow:

* Run without executable jar because it use spring-boot-devtools
* Scanning target classes are stored in `$HOME/.m2/repository/com/bee/kuna/kuna-server-db/0.1.1-RELEASE/kuna-server-db-0.1.1-RELEASE.jar`
* Specified scanning base package is `com.bee`
* GroupId of artifact that stared target classes is `com.bee.kuna` -> the groupId prefix is matched with scanning base package(`com.bee`)

### Fix version

- [x] 2.0.1
- [x] 1.3.4 (backport)

**Comment by kazuki43zoo** [comment]
The valid workaround is changing the scanning base package to more nested package(e.g. `com.bee.kuna.typehandler`). 

**NOET:**
Does not support the wildcard as the scanning base package (e.g. `com.bee.*.typehandler`). If you need to scan classes from multiple package, please specify base package for each. (e.g. `mybatis.type-handlers-package=com.bee.kuna.typehandler,com.bee.foo.typehandler`)

**Comment by kazuki43zoo** [comment]
This issue's root cause are following code in  `SpringBootVFS`.

https://github.com/mybatis/spring-boot-starter/blob/ba00741f7ef3303dc69df600efe3e97018d67e8a/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java#L57-L65

In this implementation, the MyBatis will try to scan the `/com/bee/kuna/kuna-server-db/0.1.1-RELEASE/kuna-server-db-0.1.1-RELEASE.jar!com/bee/kuna/typehandler/FooTypeHandler.class`.
In this case, the MyBatis should be scan `com/bee/kuna/typehandler/FooTypeHandler.class`.

I think `uriStr.indexOf(rootPath);` should be changed to `uriStr.lastIndexOf(rootPath); `.

**Comment by kazuki43zoo** [comment]
@eddumelendez WDYT? Is correct my suggestion?

**Comment by kazuki43zoo** [comment]
@wamaco

Thanks for your report! 
I propose to apply workaround until fix this issue. See https://github.com/mybatis/spring-boot-starter/issues/301#issuecomment-475143033.

**Comment by kazuki43zoo** [comment]
Hi @wamaco,

I've fixed this and published snapshot version(2.0.1-SNAPSHOT, 1.3.4-SNAPSHOT) to OSS nexus. If you are time, please check it.
About how to use snapshot version, see here[https://github.com/mybatis/mybatis-3/wiki/Maven#snapshot].

Thanks!

**Comment by wamaco** [comment]
Hi @kazuki43zoo , thank you very much.
I have tested my code with 1.3.4-SNAPSHOT, and the warnings have disappeared.

I have a little suggestion,  `TypeHandler` check all `com.bee` subpackages, now we can configure multiple packages like `com.bee.kuna, com.bee.test, ...`, but if we can configure it as`com.bee.*.typehandler.*` will be great,  like aspectj scanning do. 
```
2019-03-28 10:57:30.323 DEBUG 37605 --- [  restartedMain] org.apache.ibatis.io.ResolverUtil        : Checking to see if class com.bee.kuna.server.logging.AccessLoggingProperties matches criteria [is assignable to TypeHandler]
2019-03-28 10:57:30.323 DEBUG 37605 --- [  restartedMain] org.apache.ibatis.io.ResolverUtil        : Checking to see if class com.bee.kuna.server.logging.AccessLoggingFilter matches criteria [is assignable to TypeHandler]
```

**Comment by naoki-iwami** [comment]
日本語にて失礼します。
こちら、現在のプロジェクトで試した（1.3.4-SNAPSHOT）ところ問題なく動きました。
該当のケースかどうかはわかりませんが、以下のような構成です。

```[Spring config class (kotlin)]
@Indexed
@Configuration
@MapperScan(basePackageClasses = [ InfraConfig::class ], annotationClass = MybatisMapper::class)
@Profile("!ignore_mybatis")
class InfraDataSourceConfiguration {

    @Bean
    @Throws(Exception::class)
    fun sqlSessionFactory(dataSource: DataSource): SqlSessionFactory {
        val sessionFactory = SqlSessionFactoryBean()
        sessionFactory.setDataSource(dataSource)
        sessionFactory.setConfigLocation(ClassPathResource("/mybatis-config.xml"))
        sessionFactory.setFailFast(true)
        sessionFactory.vfs = SpringBootVFS::class.java
        return sessionFactory.`object`!!
    }

}

[mybatis-config.xml]
<configuration>
    <typeAliases>
        <typeAlias alias="velocity" type="org.mybatis.scripting.velocity.Driver"/>
        <package name="xxx.yyy" /><!-- このパッケージ配下にある @Alias をスキャンする -->
    </typeAliases>
</configuration>```

**Comment by kazuki43zoo** [comment]
@wamaco Thanks for your working!

> I have a little suggestion, TypeHandler check all com.bee subpackages, now we can configure multiple packages like com.bee.kuna, com.bee.test, ..., but if we can configure it ascom.bee.*.typehandler.* will be great, like aspectj scanning do.

I will consider to support it!

**Comment by kazuki43zoo** [comment]
@wamaco I've created #314.

**Comment by wamaco** [comment]
> @wamaco I've created #314.

@kazuki43zoo thanks, I have subscribed, and I'm learning from you.
