### ISSUE TITLE
this config has No effect

### ISSUE THREAD

**Issue by sunlin901203** [mybatis/spring-boot-starter#35]
mybatis.mapperLocations[0]=classpath:/mybatis/**Mapper.xml

this config has No effect

when i use SqlSessionTemplate to select database,error occur,the information is java.lang.IllegalArgumentException: Mapped Statements collection does not contain value for com.xx.xx

**Comment by kazuki43zoo** [comment]
Please describe detail. What is problem ?

**Comment by kazuki43zoo** [comment]
Hi, @sunlin901203 

Can you provide a repro project on GitHub ?

**Comment by sunlin901203** [comment]
this is my project .https://github.com/sunlin901203/example-spring-boot

**Comment by kazuki43zoo** [comment]
@sunlin901203 

In current implementation of mybatis-spring-boot, `mybatis.config` and `mybatis.xxxx` properties cannot use together.
See https://github.com/mybatis/mybatis-spring-boot/blob/master/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java#L109-L123.

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez ,I think that it is better to solve this limitation(`mybatis.config` and `mybatis.xxxx` properties cannot use together.).
At least, i think should be describe this limitation on documentation(`README.md` and JavaDoc).

What do you think ?

**Comment by kazuki43zoo** [comment]
@sunlin901203 

Other limitation(known issue) for mybatis-spring-boot's auto-configuration is as follow:

* https://github.com/mybatis/spring/pull/119

Package scanning for type aliases and type handlers does not work when configure by mybatis-spring-boot's auto-configuration using `application.properties` or `application.yml`.
The workaround for this issue is to use `mybatis-config.xml`.

**Comment by sunlin901203** [comment]
ok,thank you very much.

**Comment by eddumelendez** [comment]
Currently, you can not use `xml` and `annotations` together. This is a limitation for now. About, the limitation @kazuki43zoo mentioned 

> Package scanning for type aliases and type handlers does not work when configure by mybatis-spring-boot's auto-configuration using application.properties or application.yml.

It has been solved in 1.0.1 adding a [SpringBootVFS](https://github.com/mybatis/mybatis-spring-boot/blob/master/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java) by default in the `SqlSessionFactory`

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez 

Probably, it work when use `mybatis-config.xml` as follow:

```xml
<typeAliases>
  <package name="domain.model"/>
</typeAliases>

<typeHandlers>
  <package name="infra.mybatis.typehandler"/>
</typeHandlers>
```

But, it does not work when use `application.properties` or `application.yml` as follow:

```properties
mybatis.typeAliasesPackage=domain.model
mybatis.typeHandlersPackage=infra.mybatis.typehandler
```

The `SqlSessionFactoryBean` cannot scan classes from specified package because custom VFS does not applied to MyBatis's configuration object until mybatis-spring 1.2.4.
This issues will resolve by mybatis/spring#119 (mybatis-spring 1.2.5 or 1.3.0).

My understanding is wrong ?

**Comment by eddumelendez** [comment]
@kazuki43zoo in `mybatis-spring` 1.2.4 we added the support for a custom VFS https://github.com/mybatis/spring/commit/c8ecb3ca6dd05bc22b828702abd377fb68ab964d and `mybatis-spring-boot` 1.0.1 also support this https://github.com/mybatis/spring/commit/5c643b0e4ba3abf0db055a3fac23973b662fcaa0 

I tested this with an example and it works. I also saw your commit https://github.com/mybatis/spring/commit/8c92989a34f531243761ed783e39057c33a7dd50

**Comment by kazuki43zoo** [comment]
@eddumelendez 

My changes of https://github.com/mybatis/spring/commit/8c92989a34f531243761ed783e39057c33a7dd50 is need.
This issue occurred  on running a (Fully) executable jar (`java -jar xxxx.jar`). (it does not occurred on running a IDE such as IntelliJ IDEA..)

**Note:**
My application is multi modules of maven.
For my application, refer to https://github.com/kazuki43zoo/spring-boot-multi-sample.
The MyBatis is used on `domain` module.
Spring Boot Applications(`screen-xxx` module etc...) has depend on `domain` module.

What do you think ?
And i can provide a more simple repro project at later. Is need ?

**Comment by eddumelendez** [comment]
@kazuki43zoo I understand the need. It was solved in gh-21 which is part of `mybatis-spring-boot` 1.0.1. You can try now using the released version and provide feedback. That's the reason why I don't see any change in that class just moving some lines.

If there are any issue please add a new one related to that topic. Thanks

**Comment by kazuki43zoo** [comment]
@eddumelendez 

I use mybatis-spring-boot 1.0.1 already. However package scanning does not work when use mybatis-spring 1.2.4.

> If there are any issue please add a new one related to that topic. Thanks

OK. I will add new issue this topics.

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez , i create the #38 .
