### ISSUE TITLE
mybatis-spring-boot-starter-test:2.0.2 is missing at Maven Central

### ISSUE THREAD

**Issue by zoosm3** [mybatis/spring-boot-starter#372]
Hello,

We are using mybatis-spring-boot-starter:2.0.2 and mybatis-spring-boot-starter-test:2.0.2.

However, mybatis-spring-boot-starter-test:2.0.2 doesn't exist at Maven Central as of 7/24. 
https://repo.maven.apache.org/maven2/org/mybatis/spring/boot/mybatis-spring-boot-starter-test/
As far as we remember, we could get mybatis-spring-boot-starter-test:2.0.2 before mybatis-spring-boot-starter:2.1.0 released.

Is it better for us to use mybatis-spring-boot-starter-test:2.1.0 instead of 2.0.2?

Thanks in advance,

**Comment by kazuki43zoo** [comment]
Hi @zoosm3 , Please use the 2.1.0[1] together with Spring Boot 2.1+. There is no plan to release 2.0.2 at now. The 2.0.x line supports the Spring Boot 2.0.x. But Spring Boot 2.0.x is EOL already. About GA version, see the http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Requirements.

[1] For details, see https://github.com/mybatis/spring-boot-starter/releases/tag/mybatis-spring-boot-2.1.0.
