### ISSUE TITLE
Can release 2.0.2 with mybatis-spring-2.0.2? Because it fixed "There is case that fail to register type alias when exists anonymous class since mybatis-spring 2.0.1 #362"

### ISSUE THREAD

**Issue by yuanjinyong** [mybatis/spring-boot-starter#373]
I have see the following description in mybatis-spring-boot-2.0.1 release note.
`This release will become the final maintenance version for Spring Boot 2.0.x based.`

But mybatis-spring-boot-2.0.1 used mybatis-spring-2.0.1, and if the model or entity class with an inner class, there will be an issue https://github.com/mybatis/spring/issues/362.
This issue had fixed in mybatis-spring-2.0.2 version.

We have a lot of code with inner class like following, and can't upgrade spring boot to 2.1.x version because we used Spring Cloud Finchley.
```
public class EquipmentEntity extends BaseEntity<Long> {
    public static final class LendStatus {
        public static final Integer NORMAL = 101; // 正常
        public static final Integer LEND = 102; // 借出
        public static final Integer LOAN = 103; // 外借
    }

    public static final class Status {
        public static final Integer NORMAL = 101; // 正常
        public static final Integer SUSPEND = 102; // 停用
        public static final Integer DISCARD = 103; // 报废
    }

    private static final long serialVersionUID = -2096500653734894782L;

    @ApiModelProperty(position = 1010, value = "设备类别ID", required = true, example = "FJ-GJ")
    private String f_category_id; // 设备类别ID
}
```

**Comment by kazuki43zoo** [comment]
Hi @yuanjinyong , Please update to mybatis-spring 2.0.2 individually as follow:

* pom.xml

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.mybatis</groupId>
        <artifactId>mybatis-spring</artifactId>
        <version>2.0.2</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

```

**Comment by yuanjinyong** [comment]
yes, I just added the following dependencies as a temporary resolution.
```
dependencies {
    compile "org.mybatis.spring.boot:mybatis-spring-boot-starter:2.0.1"
    compile "org.mybatis:mybatis-spring:2.0.2" // There is case that fail to register type alias when exists anonymous class since mybatis-spring 2.0.1 #362
    compile "org.mybatis:mybatis:3.5.2"
}
```

**Comment by kazuki43zoo** [comment]
> yes, I just added the following dependencies as a temporary resolution

Thanks for applying workaround ! At now, there is no plan to release the mybatis-spring-boot-starter 2.0.2(because 2.0.x line is EOL). Please understand  our maintenance policy.
