### ISSUE TITLE
lazyload and secend level cache throw ClassCastException

### ISSUE THREAD

**Issue by Jnoee** [mybatis/spring-boot-starter#379]
```java
@Mapper
@CacheNamespace
public interface UserDao {
  User getByUsername(String username);
  ...
}
```
```java
public class User {
  private Organ organ; // lazy load field
}
```

UserDao.getByUsername return a proxy object.

then cache hit, throw 
java.lang.ClassCastException: x.y.z.User_$$_jvste83_2 cannot be cast to x.y.z.User

**Comment by kazuki43zoo** [comment]
@Jnoee Could you provide small reproduce project via GitHub?

**Comment by kazuki43zoo** [comment]
@Jnoee What status? If no reply, I will close this issue.

**Comment by kazuki43zoo** [comment]
@Jnoee  Closed because no reply.
