### ISSUE TITLE
when MySQL column has underline , @Select("select * ...")  cannot autofill the corresponding property,it will be NULL

### ISSUE THREAD

**Issue by co1d** [mybatis/spring-boot-starter#411]
version: 2.1.1

**Comment by kazuki43zoo** [comment]
Is specify the [`mapUnderscoreToCamelCase=true`](https://mybatis.org/mybatis-3/configuration.html#settings)?

* application.properties

```properties
mybatis.configuration.map-underscore-to-camel-case=true
```

**Comment by co1d** [comment]
> Is specify the [`mapUnderscoreToCamelCase=true`](https://mybatis.org/mybatis-3/configuration.html#settings)?
> 
> * application.properties
> 
> ```ini
> mybatis.configuration.map-underscore-to-camel-case=true
> ```
thank you ,this configuration works
