### ISSUE TITLE
Library version inconsistency notice.

### ISSUE THREAD

**Issue by calvinhkf** [mybatis/spring-boot-starter#423]
Hi. I have implemented a tool to detect library version inconsistencies. Your project have 1 inconsistent library and 1 false consistent library.

Take org.mybatis.scripting:mybatis-velocity for example, this library is declared as version 2.0 in mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity-legacy, 2.1.0 in mybatis-spring-boot-autoconfigure and etc... Such version inconsistencies may cause unnecessary maintenance effort in the long run. For example, if two modules become inter-dependent, library version conflict may happen. It has already become a common issue and hinders development progress. Thus a version harmonization is necessary.

Provided we applied a version harmonization, I calculated the cost it may have to harmonize to all upper versions including an up-to-date one. The cost refers to POM config changes and API invocation changes. Take org.mybatis.scripting:mybatis-velocity for example, if we harmonize all the library versions into 2.1.0. The concern is, how much should the project code adapt to the newer library version. We list an effort table to quantify the harmonization cost. 

The effort table is listed below. It shows the overall harmonization effort by modules. The columns represents the number of library APIs and API calls(NA,NAC), deleted APIs and API calls(NDA,NDAC) as well as modified API and API calls(NMA,NMAC). Modified APIs refers to those APIs whose call graph is not the same as previous version. Take the first row for example, if upgrading the library into version 2.1.0. Given that 6 APIs is used in module mybatis-spring-boot-autoconfigure, 0 of them is deleted in a recommended version(which will throw a NoMethodFoundError unless re-compiling the project),  0 of them is regarded as modified which could break the former API contract.

|Index|Module|NA(NAC)|NDA(NDAC)|NMA(NMAC)|
|-|-|-|-|-|
|1|mybatis-spring-boot-autoconfigure|6(24)|0(0)|0(0)|
|2|mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity-legacy|0(0)|0(0)|0(0)|
|3|mybatis-spring-boot-samples/mybatis-spring-boot-sample-velocity|0(0)|0(0)|0(0)|

Also we provided another table to show the potential files that may be affected due to library API change, which could help to spot the concerned API usage and rerun the test cases. 

As for false consistency, take org.mybatis.scripting mybatis-freemarker jar for example. The library is declared in version 1.2.1 in all modules. However they are declared differently.  As components are developed in parallel, if one single library version is updated, which could become inconsistent as mentioned above, may cause above-mentioned inconsistency issues

If you are interested, you can have a more complete and detailed report in the attached PDF file.
[mybatis spring-boot-starter.pdf](https://github.com/mybatis/spring-boot-starter/files/4271301/mybatis.spring-boot-starter.pdf)

**Comment by zoosm3** [comment]
I am afraid I am not sure, but I personally do not think this kind of thing might not happen if you use parent pom correctly?

**Comment by calvinhkf** [comment]
@zoosm3  I understand your concern. That's why we are developing our research tool into either a Maven or Travis plugin so that you can run it as part of CI to prevent any future regression.

BTW, can you help to confirm the detected inconsistencies? Will you fix them? Or you won't potentially because they are intentially kept due to heavy API incompatibilities? Any feedbacks will be useful for us to improve the tool.

**Comment by calvinhkf** [comment]
@zoosm3  I understand your concern. That's why we are developing our research tool into either a Maven or Travis plugin so that you can run it as part of CI to prevent any future regression.

BTW, can you help to confirm the detected inconsistencies? Will you fix them? Or you won't potentially because they are intentionally kept due to heavy API incompatibilities? Any feedbacks will be useful for us to improve the tool.

**Comment by kazuki43zoo** [comment]
@calvinhkf

At first, thank you for your reporting and sorry for the late reaction.
Part of the sample projects(`mybatis-spring-boot-sample-*-legacy`) intentionally depend on the old version to verify backward compatibility, but I think that there is no problem because the versions used in other projects are centrally managed (basically use latest version). Hence; I've closed this issue. If you feel to remain a problem, please explain a reason.
