### ISSUE TITLE
Property 'mapperLocations' was not specified or no matching resources found

### ISSUE THREAD

**Issue by kanouken** [mybatis/spring-boot-starter#44]
HI 
    i use the "mybatis.mapperLocations"  property , then i got that message

**Comment by eddumelendez** [comment]
@kanouken can you try with `mybatis.mapper-locations`?

**Comment by kanouken** [comment]
@eddumelendez   tried too ,  the same problem

**Comment by eddumelendez** [comment]
Can you provided a sample project to reproduce, please? Thanks

**Comment by kanouken** [comment]
@eddumelendez  if i specified the "mybatis.config" , the  "mapperLocations" would not be work!
 so 
`#mybatis.config=classpath:mybatis-config.xml
mybatis.mapperLocations=classpath:com/ost/mendale/xml/*.xml`  do  his job!

**Comment by eddumelendez** [comment]
@kanouken this is not already supported. At this time, you can use just `mybatis.config` or the other properties. In the next release 1.0.2 you will be able to do that.

**Comment by kanouken** [comment]
@eddumelendez  thanks !
