### ISSUE TITLE
Get No MyBatis mapper was found in xxx package when config multi datasource

### ISSUE THREAD

**Issue by pppppkun** [mybatis/spring-boot-starter#457]
My spring-boot project can run successfully in my windows10, but when I packaged it and put it up in my ubuntu 16.04 serve, I got 
WARN: No MyBatis mapper was found in xxxxx package. Please check your configuration.
I have check my configuration many times but I don't know what happen, it's the problem caused by the File system or file path which different between windows and linux?

Here is my configuration:
![image](https://user-images.githubusercontent.com/43557766/83365912-50afff00-a3de-11ea-8cf5-608a0dc45f85.png)
![image](https://user-images.githubusercontent.com/43557766/83365915-59083a00-a3de-11ea-9bec-4cd0b26b1270.png)
![image](https://user-images.githubusercontent.com/43557766/83365919-602f4800-a3de-11ea-948c-ea1afab3cef7.png)

Here is my serve condition:
![image](https://user-images.githubusercontent.com/43557766/83365933-776e3580-a3de-11ea-8a4f-ce74ccf4b1a6.png)

**Comment by pppppkun** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.autoconfigure.availability.ApplicationAvailabilityAutoConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available

**Comment by kazuki43zoo** [comment]
@pppppkun 

Please try to set the `SpringBootVFS.class` to the `SqlSessionFactoryBean` instance and report again for this issue.
About the `SpringBootVFS.class` , please see http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Using_the_SpringBootVFS .

Thanks.

**Comment by pppppkun** [comment]
> @pppppkun
> 
> Please try to set the `SpringBootVFS.class` to the `SqlSessionFactoryBean` instance and report again for this issue.
> About the `SpringBootVFS.class` , please see http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Using_the_SpringBootVFS .
> 
> Thanks.

@kazuki43zoo 

![image](https://user-images.githubusercontent.com/43557766/83376203-017cc500-a404-11ea-9646-07f45532275d.png)
I have set the `SpringBootVFS.class` to the `SqlSessionFactoryBean`, but on my serve still reports an same error, whether my `application.yml` or the `Application.class` have wrong configuration or miss some Annotation?

**Comment by kazuki43zoo** [comment]
@pppppkun 

Could you provide a small reproduce project via GitHub?

**Comment by kazuki43zoo** [comment]
>  it's the problem caused by the File system or file path which different between windows and linux?

I don't know only by provided information. 
The most famous difference is the case-sensitive or not at file path. The Windows is case-insensitive.

**Comment by pppppkun** [comment]
> @pppppkun
> 
> Could you provide a small reproduce project via GitHub?

@kazuki43zoo 
I have invited you to a private project

**Comment by kazuki43zoo** [comment]
> I have invited you to a private project

I understand. But I cannot investigate a cause of this issue by current information. If you have a time, I will propose to create a small reproduce project similar with your application. If you can provide a small reproduce project, there is possible that I can help you. Please consider it.

Thanks.

**Comment by pppppkun** [comment]
> > I have invited you to a private project
> 
> I understand. But I cannot investigate a cause of this issue by current information. If you have a time, I will propose to create a small reproduce project similar with your application. If you can provide a small reproduce project, there is possible that I can help you. Please consider it.
> 
> Thanks.

The private project I invited you is a small reproduce project which does not have any private information

**Comment by kazuki43zoo** [comment]
@pppppkun 

Oh.. Sorry, I had a misunderstanding.
Thanks for your invitation on your reproduce project! 
I will try it and feedback at later.

**Comment by kazuki43zoo** [comment]
@pppppkun 

Please try change the `FinTech4good` to `FinTech4Good` in package name at `FinTech4GoodConfig`. (`g` -> `G`)

```diff
-@MapperScan(basePackages = "cn.edu.nju.fintech4good.dao.FinTech4good", sqlSessionFactoryRef = "FinTech4GoodSessionFactory")
+@MapperScan(basePackages = "cn.edu.nju.fintech4good.dao.FinTech4Good", sqlSessionFactoryRef = "FinTech4GoodSessionFactory")
```

**Comment by pppppkun** [comment]
> @pppppkun
> 
> Please try change the `FinTech4good` to `FinTech4Good` in package name at `FinTech4GoodConfig`. (`g` -> `G`)
> 
> ```diff
> -@MapperScan(basePackages = "cn.edu.nju.fintech4good.dao.FinTech4good", sqlSessionFactoryRef = "FinTech4GoodSessionFactory")
> +@MapperScan(basePackages = "cn.edu.nju.fintech4good.dao.FinTech4Good", sqlSessionFactoryRef = "FinTech4GoodSessionFactory")
> ```

Successfully deployed! Thank you very much.
