### ISSUE TITLE
All interfaces are registered as mybatis mappers even if they are not mappers

### ISSUE THREAD

**Issue by emacarron** [mybatis/spring-boot-starter#46]
Right now, the mybatis boot starter module takes all the interfaces it founds in a project and registers them as mappers. We should be able to identify if an interface is a mapper or not.

The problem is that mappers are not annotated (the @Mapper annotation does not exist). We did this because we would like to build applications with no mybatis imports at all. So they way you select your mappers when using classic configuraiton like MapperScannerConfigurer or @MapperScan is by:
- specifiying a base package
- specifiying a marker interface
- specifiying a marker annotation

So, my proposal is to use this convention: mappers are supposed to be interfaces held in a **/mapper or **/mappers package. 

For any other configuration, use the @MapperScan annotation that lets you configure everything.

**Comment by mallim** [comment]
While waiting for this fix, is there anyway to disable the MapperScan from happening? Any example?

**Comment by emacarron** [comment]
Yes. Add a @MapperScan to your main application pointing to a dummy interface. That will register a MapperFactoryBean and default scanning will not start.

**Comment by mallim** [comment]
Thanks for the example, I think this is a good material to put in the docs. If not, people will have to come to this issue and read about this...

Anyway, this is what is working for my case:

```
@Configuration
@MapperScan("dummy")
public class MybatisConfig {

   @Bean
   public ActualMapper mapper(SqlSessionFactory sqlSessionFactory){
        SqlSessionTemplate sessionTemplate = new SqlSessionTemplate( sqlSessionFactory );
        return sessionTemplate.getMapper(ActualMapper.class);
   }
}

```
dummy package contains an interface:

```
public interface DummyMapper {
}
```

whereby my mybatis-config.xml has some mappers

hope this will help someone ...

**Comment by emacarron** [comment]
Good to know! BTW, I am curious about this. Do you want to turn off scanning? if so, why?

**Comment by mallim** [comment]
I am using this way to avoid all interfaces to be registered as mybatis mappers even if they are not mappers. Actually, can we have a setting to turn off the @MapperScan ?

For example:

```
mybatis:
   scanning: true 
```

**Comment by emacarron** [comment]
@mallim But... note that a mapper must be a bean in spring so it can be injected into any other bean. How are you registering your mapper? (or are you using the sqlSessionTemplate?)

**Comment by mallim** [comment]
Hi @emacarron 

I registered all the mappers by using this way:

```
@Configuration
@MapperScan("dummy")
public class MybatisConfig {

   @Bean
   public ActualMapper1 mapper(SqlSessionFactory sqlSessionFactory){
        SqlSessionTemplate sessionTemplate = new SqlSessionTemplate( sqlSessionFactory );
        return sessionTemplate.getMapper(ActualMapper1.class);
   }

   @Bean
   public ActualMapper2 mapper(SqlSessionFactory sqlSessionFactory){
        SqlSessionTemplate sessionTemplate = new SqlSessionTemplate( sqlSessionFactory );
        return sessionTemplate.getMapper(ActualMapper2.class);
   }
}
```

spring-boot-starter works with this pattern since 1.0 :+1:

**Comment by emacarron** [comment]
I see, but I would say you have too much boilerplate.

If you set the @MapperScan()  with the package name (or pattern) where your mappers are this will work fine and you can remove that two @Bean methods. 

Can you check that?

**Comment by emacarron** [comment]
BTW I just have updated master so autoscanning will only pick interfaces inside **/mapper or **/mappers package as a convention (over configration).

@kazuki43zoo I finally decided not to include "repository" to let people mix JPA and MyBatis in the same project. 

Can you plese check the snapshot and let us know how it works?

**Comment by kazuki43zoo** [comment]
@emacarron 

OK, i agree with your decision !!
I think this change should will be announced expressly on release note.

Thanks!

**Comment by emacarron** [comment]
Sure. And thanks for your opinion!

**Comment by mallim** [comment]
@emacarron 

My boilerplate way is still better than having this log appearing 

````
2016-04-08 14:20:33.381  WARN 4828 --- [           main] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'XXXRepository' and 'XXXRepository' mapperInterface. Bean already defined with the same name!
````

And for trying to do this :-)

`@MapperScan("pkg1,pkg2,pkg3,pkg4")`

**Comment by emacarron** [comment]
You can specify a pattern in basepackage. You may want to try that.

**Comment by emacarron** [comment]
I have recoded this to be more aligned with Spring @Configuration that is based on annotations. So I have added a @Mapper marker annotation to the core so other DI frameworks can use it (spring, boot, cdi)

Thoughts?

**Comment by jeffgbutler** [comment]
I think that's a good idea.

**Comment by mallim** [comment]
@emacarron 

This is a very good idea :+1:

**Comment by mnesarco** [comment]
Hi @emacarron I didn't know about this Mapper annotation in advance so I have added one in CDI some time ago just before 1.0 release. Do you think we have to remove the cdi specific annotation and use just this?

**Comment by marwin1991** [comment]
I am using 3.5.6 And this still happens And belive me I is so crap as ****.
