### ISSUE TITLE
[mybatis-spring-boot] DI error due to multiple DI contexts ?

### ISSUE THREAD

**Issue by fcamblor** [mybatis/spring-boot-starter#467]
Hi there, 

I'm facing a weird Spring dependency injection issue while bootstrapping a new application based on Spring Boot + MyBatis.

My dependencies are :
- spring-boot-starter-parent@2.1.3
- mybatis-spring-boot-starter@2.1.3 (which pull mybatis@3.5.5 and mybatis-spring@2.0.5)

When I create a simple repository like that :

    @Repository
    public class SampleRepository extends SqlSessionDaoSupport {
      public List<String> selectAllNames() {
        return this.getSqlSession().selectList("com.samples.SampleRepository.select-all-lists");
      }
    }

And I try to use/inject it anywhere, I get following error message :

    Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

This check comes from `mybatis-spring`'s `SqlSessionDaoSupport` checks that are called during `afterPropertiesSet` (see [here](https://github.com/mybatis/spring/blob/mybatis-spring-2.0.5/src/main/java/org/mybatis/spring/support/SqlSessionDaoSupport.java#L122) and [there](https://github.com/spring-projects/spring-framework/blob/v5.1.5.RELEASE/spring-tx/src/main/java/org/springframework/dao/support/DaoSupport.java#L44))

This check is supposed to be in failure if no `sqlSessionTemplate` has been created (meaning no `SqlSessionTemplate` nor `SqlSessionFactory` spring bean has been provided to the spring context).
However, looking at `MybatisAutoConfiguration`'s implementation ([here](https://github.com/mybatis/spring-boot-starter/blob/mybatis-spring-boot-2.1.3/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfiguration.java#L132)) I can see that the auto-configuration is supposed to create it.

I tried to debug everything, and I came to the conclusion that I had sort of multiple spring application contexts : if I inject `ApplicationContext` into my `SampleRepository` bean, I can see that during the `afterPropertiesSet()` call, a `SqlSessionTemplate` and `SqlSessionFactory` exist into the global spring application context while, at the same time, those have not been injected through dependency injection.

I created a sample project [here](https://github.com/fcamblor/spring-boot-mybatis-sample) to demonstrate the issue.

You will see that if I change my `SampleRepository`'s implementation to this :
```
@Repository
public class SampleRepository extends SqlSessionDaoSupport {

  private final ApplicationContext applicationContext;

  protected SampleRepository(ApplicationContext applicationContext) {
    super();
    this.applicationContext = applicationContext;
  }

  @Override
  protected void checkDaoConfig() {
    // Don't know why, but late injection doesn't work here, and we need to do things ourselves
    // which is weird !
    if(this.getSqlSessionTemplate() == null && this.getSqlSessionFactory() == null) {
      logger.info("SqlSession* ARE NULL");
      if(applicationContext.getBeanNamesForType(SqlSessionTemplate.class).length != 0) {
        this.setSqlSessionTemplate(applicationContext.getBean(SqlSessionTemplate.class));
      } else if(applicationContext.getBeanNamesForType(SqlSessionFactory.class).length != 0) {
        this.setSqlSessionFactory(applicationContext.getBean(SqlSessionFactory.class));
      }
    } else {
      logger.info("SqlSession* ARE NOT NULL");
    }

    super.checkDaoConfig();
  }

  public List<String> selectAllNames() {
    return this.getSqlSession().selectList("com.samples.SampleRepository.select-all-lists");
  }
}
```
... then it works !

Which looks very weird to me.

I'm feeling there are kind of multiple spring context, and the one used during my `SampleRepository`'s initialization doesn't have access to the spring context containing `SqlSessionTemplate` and `SqlSessionFactory` beans (while the "root" Application context has access to them)

How can I debug such issue ?
Would someone be willing to help ?

Thanks in advance,

**Comment by kazuki43zoo** [comment]
@fcamblor 

Unfortunately, the `SqlSessionDaoSupport` does not support autowiring with annotation based component scanning because the `SqlSessionDaoSupport`'s setter methods no define the `@Autowired`.

I will propose to resolve this issue following two solutions.

1. Inject a SqlSession(SqlSessionTemplate) directly each repository class

```java
@Repository
public class SampleRepository {
  private final SqlSession sqlSession;
  public SampleRepository(SqlSession sqlSession) {
    this.sqlSession = sqlSession;
  }
  public List<String> selectAllNames() {
    return this.sqlSession.selectList("com.samples.SampleRepository.select-all-lists");
  }
}
```

2. Creating a custom DAO support class that extends SqlSessionDaoSupport

```java
import org.apache.ibatis.session.SqlSessionFactory;
import org.mybatis.spring.SqlSessionTemplate;
import org.mybatis.spring.support.SqlSessionDaoSupport;
import org.springframework.beans.factory.annotation.Autowired;

public abstract class AutowiredSqlSessionDaoSupport extends SqlSessionDaoSupport {

  @Autowired(required = false)
  @Override
  public void setSqlSessionFactory(SqlSessionFactory sqlSessionFactory) {
    super.setSqlSessionFactory(sqlSessionFactory);
  }

  @Autowired(required = false)
  @Override
  public void setSqlSessionTemplate(SqlSessionTemplate sqlSessionTemplate) {
    super.setSqlSessionTemplate(sqlSessionTemplate);
  }

}
```

```java
@Repository
public class SampleRepository extends AutowiredSqlSessionDaoSupport {
  public List<String> selectAllNames() {
    return this.getSqlSession().selectList("com.samples.SampleRepository.select-all-lists");
  }
}
```

**Comment by fcamblor** [comment]
pfff, I'm feeling ashamed to not have spotted a that simple cause.

My brain took the autowiring shortcut as soon as he saw the public setters.

It's working fine thanks, will close the issue.

One question though : any special reason behing the `required=false` flag on the `@Autowired` setters in your 2nd example ?

**Comment by kazuki43zoo** [comment]
> any special reason behing the required=false flag on the @Autowired setters in your 2nd example ?

This is because it is sufficient to set either one component(`SqlSessionFactory` or `SqlSessionTemplate`). If set `required=true` (or omit an attribute), we should need to register both components into `ApplicationContext`.

Note: We will consider to add `@Autowired` into `SqlSessionDaoSupport` or creating new class on spring-mybatis module at future version.
