### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by lvhuafu** [mybatis/spring-boot-starter#472]
I just change mybatis-spring-boot-starter 1.3.2 to 2.1.2.
1.3.2:
![1594030369(1)](https://user-images.githubusercontent.com/7557163/86582923-027db500-bfb5-11ea-9f97-f5e0338c2aa5.png)
2.1.2:
![1594030264(1)](https://user-images.githubusercontent.com/7557163/86582946-0b6e8680-bfb5-11ea-8ba6-20668d0b8e5e.png)
what happened?

**Comment by kazuki43zoo** [comment]
@lvhuafu

You should be explained an actually problem on your application. What problem did by this different? We cannot anser by provided information.

Note: It may be due to a change in spring-projects/spring-framework#22461. Please check it.

**Comment by kazuki43zoo** [comment]
I've closed because no reply. please reopen this if need.
