### ISSUE TITLE
Mapper sanncer cannot scan the packages specified by @ComponentScan

### ISSUE THREAD

**Issue by eason-zhang1** [mybatis/spring-boot-starter#493]
when I use @ComponentScan in the bootstrap class, the interfaces with @Mapper annotation in the packages specified by @ComponentScan cannot be registered. In  MybatisAutoConfiguration( mybatis-spring-boot-autoconfigure), i found the code
`List<String> packages = AutoConfigurationPackages.get(this.beanFactory);`, this only get the packages of the bootstrap class.

**Comment by kazuki43zoo** [comment]
Mapper interfaces cannot scan using `@ComponentScan`. If you can scan mapper interfaces form any package, please use the mapper scan feature provided by mybatis-spring (ex. `@MapperScan`).

http://mybatis.org/spring/mappers.html#scan
