### ISSUE TITLE
Why do I have to add @MapperScan in App to scan mapper although App and Mapper are in the same package?

### ISSUE THREAD

**Issue by ppzzyy11** [mybatis/spring-boot-starter#510]
I meet the same problem in my project where I try to @Autowired a mapper from another model.
The annotation in @SpringBootApplication(scanBasePackage={"com.example.mvcdemo"}) scans every class except mapper. Here is my project directory. 
**WHY?**

This issue is similar to mine. https://github.com/mybatis/spring-boot-starter/issues/153.

![image](https://user-images.githubusercontent.com/20295482/97781699-29956d80-1bc8-11eb-95c4-c43bb92a7457.png)

**Comment by harawata** [comment]
Hello @ppzzyy11 ,

There is not enough information.
Please share the project on your GitHub repository and we'll look into it.

**Comment by ppzzyy11** [comment]
> Hello @ppzzyy11 ,
> 
> There is not enough information.
> Please share the project on your GitHub repository and we'll look into it.

https://github.com/ppzzyy11/mvcDemo

**Comment by harawata** [comment]
Thanks for the project, @ppzzyy11 !

There is a note in the [document](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html#scanBasePackages--) of `@SpringBootApplication#scanBasePackages`.

> Note: this setting is an alias for @ComponentScan only. It has no effect on @Entity scanning or Spring Data Repository scanning. For those you should add @EntityScan and @Enable...Repositories annotations.

MyBatis' mappers are not components either, that may explain why `scanBasePackages` has no effect and you need to add `@MapperScan`.

p.s.
I'm not sure if this is officially supported, but another solution is to move the `Application` class from `com.example.mvcdemo.start.Application` to `com.example.mvcdemo.Application`.
It changes the application's `basePackage` which is used by [MapperScannerConfigurer](https://github.com/mybatis/spring/blob/master/src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java) when scanning mappers.

**Comment by harawata** [comment]
> Only when I add annotation "@configuration" on the MybatisDemoConfig.java can the App autowired the Mapper.

Without `@Configuration`, Spring does not recognize the class as a configuration class.
The [javadoc](https://mybatis.org/spring/apidocs/org/mybatis/spring/annotation/MapperScan.html) of `@MapperScan` contains an example.

**Comment by ppzzyy11** [comment]
> Thanks for the project, @ppzzyy11 !
> 
> There is a note in the [document](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/SpringBootApplication.html#scanBasePackages--) of `@SpringBootApplication#scanBasePackages`.
> 
> > Note: this setting is an alias for @componentscan only. It has no effect on @entity scanning or Spring Data Repository scanning. For those you should add @EntityScan and @enable...Repositories annotations.
> 
> MyBatis' mappers are not components either, that may explain why `scanBasePackages` has no effect and you need to add `@MapperScan`.
> 
> p.s.
> I'm not sure if this is officially supported, but another solution is to move the `Application` class from `com.example.mvcdemo.start.Application` to `com.example.mvcdemo.Application`.
> It changes the application's `basePackage` which is used by [MapperScannerConfigurer](https://github.com/mybatis/spring/blob/master/src/main/java/org/mybatis/spring/mapper/MapperScannerConfigurer.java) when scanning mappers.

Yeah. Thanks for your time.  I really get confused by the second solution in case that I have declare that the scanBasePackages as com.example.mvcdemo but still get a "Can not autowired" error.

**Comment by kazuki43zoo** [comment]
Hi @ppzzyy11 ,

In default behavior of MyBatis autoconfigure, it scan mapper interfaces from packages of class annotated with `@SpringBootApplication`. If you want to change this behavior, you need to use the `@MapperScan`.
The MyBatis autoconfigure not use the `scanBasePackages` attribute of `@SpringBootApplication` for scanning mapper interfaces.

**Comment by kazuki43zoo** [comment]
Close this issue because no reply.
