### ISSUE TITLE
Kotlin & Spring Boot - I have a MyBatis mapper that I'm “monkey patching” a method onto and need an autowired bean in the method

### ISSUE THREAD

**Issue by mikebski** [mybatis/spring-boot-starter#531]
I have an interface in Kotlin that is a MyBatis mapper:

```
@Mapper
interface EquipmentSupportMapper {
    // @Autowired lateinit var metaMapper: MetaMapper // <- Does not work... How?
    @SelectProvider(type = SqlProviderAdapter::class, method = "select")
    fun findMany(selectStatement: SelectStatementProvider?): List<Equipment>
}
```

I then add a method implementation into it:

```
fun EquipmentSupportMapper.searchEquipment(
    textSearchValue: String? = null, facilities: Array<Int>? = null,
    manufacturers: Array<Int>? = null, equipmentExample: Equipment? = null
):
        List<Equipment> {
    val builder = SqlBuilder.select(equipmentColumnList)
        .from(EquipmentSupport.EquipmentTable)
        .where()
...
return someList;
```

Now, in my method searchEquipment I need to @Autowire a spring bean called MetaMapper.

I can't just add:

`@Autowired lateinit var metaMapper: MetaMapper` in the interface because it gives errors. 

If I make the class abstract, I get `No qualifying bean of type 'blah.EquipmentSupportMapper'`

How can I do this?

**Comment by kazuki43zoo** [comment]
@jeffgbutler Cloud you help this issue?

**Comment by mikebski** [comment]
@kazuki43zoo - I should have posted this:

```kotlin
@Mapper
@Qualifier("IESM")
interface InterfaceEquipmentSupportMapper {
    // @Autowired lateinit var metaMapper: MetaMapper // <- Does not work... How?
    @SelectProvider(type = SqlProviderAdapter::class, method = "select")
    fun findMany(selectStatement: SelectStatementProvider?): List<Equipment>
}

@Service
@Qualifier("EquipmentSupportMapper")
class EquipmentSupportMapper(
    @Autowired @Qualifier("IFSM") ifsm: InterfaceEquipmentSupportMapper,
    @Autowired metaMapper: MetaMapper
  ): InterfaceEquipmentSupportMapper by ifsm

```

The trick is to create a qualifier on the interface that Spring creates the implementation for and then inject that into the class that implements the same interface by delegating to the autowired Spring-created bean.

Then, instead of using the Mapper called IESM in my app I just autowire with the qualifier EquipmentSupportMapper instead and I get the right one.

Here's an example from a test:

```kotlin
@SpringBootTest
class EquipmentSupportMapperTest {
    @Autowired
    @Qualifier("EquipmentSupportMapper")
    lateinit var mapper: EquipmentSupportMapper
```

**Comment by mikebski** [comment]
Closing because I found the workaround

**Comment by kazuki43zoo** [comment]
Hi @mikebski , Thanks for your feedback!
