### ISSUE TITLE
Liquibase/Flyway autoconfiguration order

### ISSUE THREAD

**Issue by uladzislau-belykh** [mybatis/spring-boot-starter#537]
Hello, 

I use your starter in our project and found an issue with the autoconfiguration order. Sometimes SqlSessionFactory and SqlSessionTemplate can be configured and used before liquibase/flyway initialized the database completely. That leads to 
problems on startup in an empty environment. 

As I checked, Liquibase/Flyway AutoConfiguration provides *DependsOnPostProcessors for standard JDBC beans (JdbcTemplate and EntityManager). That ensures the order in which beans will be initialized. 

Now I added this dependency manually, but it will be nice if this will be in autoconfiguration.

Thank you in advance.

**Comment by kazuki43zoo** [comment]
Hi @uladzislau-belykh , Thanks and Sorry for the late response.

We will consider to support the DependsOnPostProcessors on mybatis auto-configuration feature.
If possible, Could you provide a small reproduce project that occurred a problem and project that applied a workaround? We want to use it for testing.

**Comment by uladzislau-belykh** [comment]
You can find the sample [here](https://github.com/uladzislau-belykh/mybatis-test)

**Comment by eddumelendez** [comment]
#648 is merged.

**Comment by kazuki43zoo** [comment]
@uladzislau-belykh 
We resolved this issue on 2.3.0(not release yet, but you can use the [snapshot version](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/spring/boot/mybatis-spring-boot-starter/2.3.0-SNAPSHOT/)). 2.3.0 require to use together with Spring Boot 2.5+.
