### ISSUE TITLE
why SpringBootVFS not use Thread.currentThread().getContextClassLoader() as ClassLoader

### ISSUE THREAD

**Issue by haibingzhao** [mybatis/spring-boot-starter#542]
[Mybatis VFS](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/io/VFS.java#L190) getResources use `Thread.currentThread().getContextClassLoader()` as ClassLoader, but [mybatis-spring-boot-autoconfigure SpringBootVFS](https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-autoconfigure/src/main/java/org/mybatis/spring/boot/autoconfigure/SpringBootVFS.java#L40) not, this will cause resources not found.

**Comment by kazuki43zoo** [comment]
@haibingzhao 

Sorry for late reply. Thanks your reporting.
Could you provide an actual conditions(environments) that cannot found or/and the small reproduce project?

**Comment by PENGCHENGLIN007** [comment]
[SpringBootVFSTest.zip](https://github.com/mybatis/spring-boot-starter/files/9268845/SpringBootVFSTest.zip)
只要在测试程序中修改build就可以复现上述问题。
原始打包方式可以加载到com.pcl.test.typehandler.ArrayType2Handler
截图如下：
![企业微信截图_16597042783304](https://user-images.githubusercontent.com/23567280/183082813-5db5cbad-fd64-4550-a0d4-c86e6291d88d.png)

新的打包方式无法加载type handler
截图如下：
![企业微信截图_16597040501109](https://user-images.githubusercontent.com/23567280/183082942-cd63ae37-4705-42ac-94fb-d4ab7948b545.png)
