### ISSUE TITLE
Spring-boot-stater-mybatics don't throw any SQL Exception

### ISSUE THREAD

**Issue by lenguyenkhoi21** [mybatis/spring-boot-starter#547]
Hello Mybatics Team, I'm newbie using mybatics with spring boot, I've just  building simple project with mybatics. In run time, When I test a key that not database to select, there are no SQL Exception throw. Can you help me throw exception ?

**Comment by kazuki43zoo** [comment]
@lenguyenkhoi21 
Sorry for late reply. I cannot investigate this issue by provided information. Could you provide more detail information(Java version, Spring Boot version and more...) or/and the small reproduce project?
