### ISSUE TITLE
Parent version of mybatis-spring-boot-1.1.0 is wron version.

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#55]
Currently, maven build is failing on the `mybatis-spring-boot-starter` 1.1.0.
Parent version is the `28-SNAPSHOT`.
I think `27` is correct.

See http://repo1.maven.org/maven2/org/mybatis/spring/boot/mybatis-spring-boot/1.1.0/mybatis-spring-boot-1.1.0.pom

**Comment by emacarron** [comment]
Hi @kazuki43zoo Thanks for pointing. We will release 1.1.1 to fix that soon.

I will close this an leave #54 open.

**Comment by kazuki43zoo** [comment]
Oh, sorry ... i was not confirm existing issue.
