### ISSUE TITLE
MyBatis selecting SQL statement with correct databaseID value not possible in Spring boot.

### ISSUE THREAD

**Issue by jeffreyporter** [mybatis/spring-boot-starter#575]
## MyBatis version
3.x.x

## Database vendor and version
DB 11.x

## Test case or example project
https://github.com/jeffreyporter/mybatis-issue-002

we have the JDBC connection via "application.yml" file.
we have the mybatis config via "mybatis-config.xml" file.

I have a legacy Data Access layer with statements that have a database type on them.
e.g.

```xml
  <select id="getPrices" resultMap="thePriceVO"  databaseId="db2">
```

I can set an "environment" section in the mybatis-config.xml but this is too later for the JDBC connection.

I need to be able to say this connection is a "db2" connection, so that mybatis can select the correct statement.

XMLConfigBuilder.java has this code...

```

    Environment environment = configuration.getEnvironment();
    if (environment != null && databaseIdProvider != null) {
      String databaseId = databaseIdProvider.getDatabaseId(environment.getDataSource());
      configuration.setDatabaseId(databaseId);
    }

```

This seems to be the only place to set the DatabaseId, which is only called if the JDBC connection is controlled by Mybatis, not via Spring.

I don't see anyway to set the DatabaseId via a Spring controlled DB connection.

## Steps to reproduce
Start the app "TestServiceApplication"

Hit the endpoint :    curl --location --request GET 'http://localhost:8080/prices/test'

## Expected result
No exceptions.

It can select the correct mybatis statement based on Database type (DB2 vs Oracle)

## Actual result

```
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.jeff.porter.testservice.data.mapper.PriceMapper.getPrices
	at org.apache.ibatis.binding.MapperMethod$SqlCommand.<init>(MapperMethod.java:235)
	at org.apache.ibatis.binding.MapperMethod.<init>(MapperMethod.java:53)
	at org.apache.ibatis.binding.MapperProxy.lambda$cachedInvoker$0(MapperProxy.java:108)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at org.apache.ibatis.util.MapUtil.computeIfAbsent(MapUtil.java:36)
	at org.apache.ibatis.binding.MapperProxy.cachedInvoker(MapperProxy.java:95)
```

**Comment by harawata** [comment]
Hello @jeffreyporter ,

I just took a quick look, but why do you use `mybatis-config.xml` ?
As you use Spring Boot, you should add a bean definition like the following instead.

```java
@Bean
public VendorDatabaseIdProvider vendorDatabaseIdProvider() {
  VendorDatabaseIdProvider databaseIdProvider = new VendorDatabaseIdProvider();
  Properties vendorProperties = new Properties();
  vendorProperties.put("SQL Server", "sqlserver");
  vendorProperties.put("DB2", "db2");
  vendorProperties.put("Oracle", "oracle");
  databaseIdProvider.setProperties(vendorProperties);
  return databaseIdProvider;
}
```

**Comment by jeffreyporter** [comment]
That seems to resolve my issue.

Thank you.
