### ISSUE TITLE
Should I use mybatis.config-location instead of mybatis.config

### ISSUE THREAD

**Issue by syhily** [mybatis/spring-boot-starter#60]
https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-samples%2Fmybatis-spring-boot-sample-xml%2Fsrc%2Fmain%2Fresources%2Fapplication.properties#L18

See this line.

**Comment by emacarron** [comment]
Both should work. But given that config can be confused with a new parameter (configuration) then it is better that you use mybatis-location.

BTW.... the tracker is for issues, not for questions! :)
