### ISSUE TITLE
mapper override or append setting

### ISSUE THREAD

**Issue by louandme** [mybatis/spring-boot-starter#606]
how can i override the xml files ? just like UnmergeableXmlMappersPlugin , thanks.

**Comment by kazuki43zoo** [comment]
Could you explain more details and actual use cases?

**Comment by louandme** [comment]
> Could you explain more details and actual use cases?
I use an jar file code, but due to different requirements, some of the code can not meet the needs of my company, so I need to override its .xml file instead of adding mapersstatement.in this way I don't need to change its logic code,otherwise, it will do a lot of work.

**Comment by kazuki43zoo** [comment]
@louandme 
Probably you can override your custom xml file using `mybatis.mapper-locations` property (you can skip load xml file that was stored other jar file). details see https://github.com/kazuki43zoo/mybatis-spring-boot-gh-606.

**Comment by louandme** [comment]
@kazuki43zoo 

It's a little difficult to distinguish them. Their fully qualified names are the same, and other mapper and XML files have the same prefix。

![1640848124(1)](https://user-images.githubusercontent.com/53675908/147729506-23e409f6-057c-4607-b6d6-81c0ba4e95dc.png)
![1640848281(1)](https://user-images.githubusercontent.com/53675908/147729589-a93d5d0c-096f-4721-9a5c-a10f2a72631b.png)

**Comment by kazuki43zoo** [comment]
Sorry, I don't understand I don't seem to understand what you want to do...

**Comment by louandme** [comment]
I just want to say that I need to extend the usages of the jar xml file, so I need to override the mapper。
Maybe this translation is a little shit.

left is the jar xml file,which lack some fields.
right is the local xml file,their namesapce are the same,i got two same "getFile" query SQL。
That's why the mybatis exception was made,and i just want to override the xml file to append fields to the "getFile" query SQL.


![1640850614(1)](https://user-images.githubusercontent.com/53675908/147732007-91a9eb30-0f40-41a6-873a-ecf2e62a6f57.png)

**Comment by kazuki43zoo** [comment]
How about this? https://github.com/kazuki43zoo/mybatis-spring-boot-gh-606/commit/81051ba15c95d0fdf6cd3d518e1ee4bd57414962

**Comment by louandme** [comment]
i know your means,but i have so many xml files in the same prefix namespace,just like this.

should i need to create a github repository project to show you that?
![1640853865(1)](https://user-images.githubusercontent.com/53675908/147735824-86bbcdc9-c4f1-4e7b-81c5-f4b45936ac98.png)

**Comment by louandme** [comment]
org.apache.ibatis.session.Configuration -->StrictMap --> public V put(String key, V value).
change "throw new IllegalArgumentException(name + " already contains value for " + key);"  to "return get(key);".
