### ISSUE TITLE
Support Spring Boot 3

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#607]
https://github.com/mybatis/spring-boot-starter/milestone/30

**Comment by djy0** [comment]
is there a plan as when  to support sb3?

**Comment by linghengqian** [comment]
@kazuki43zoo I noticed that the version number changed and the target version that supports SpringBoot3 was changed from `2.3.0` to `3.0.0`. Is it possible to release a milestone version first, such as `2.3.0-M1` or `3.0.0-M1` to facilitate comparison and testing ?
