### ISSUE TITLE
how to initialize table data before testing?

### ISSUE THREAD

**Issue by seyoatda** [mybatis/spring-boot-starter#644]
I've read the [official doc](https://mybatis.org/spring-boot-starter/mybatis-spring-boot-test-autoconfigure/), but haven't found any tutorial about preparing data in database. So do I need to call the insert method in mapper by myself before I test the delete or update method ?

**Comment by eddumelendez** [comment]
Hi @seyoatda if you need this for testing you maybe interested in [testcontainers](https://www.testcontainers.org/)
