### ISSUE TITLE
Logging Suggested change

### ISSUE THREAD

**Issue by hazendaz** [mybatis/spring-boot-starter#66]
Currently both apache commons logging and slf4j are on the class path.  Apache commons logging, in my opinion is far less flexible than slf4j and given slf4j is already there, I think we should move to using slf4j and let it test internally for logging needs and further avoid formatting within log statements as slf4j provides that out of the box and incurs cost only when it truely needs to write the log.

**Comment by eddumelendez** [comment]
Since the PR has been merged, I will proceed to close this issue.
