### ISSUE TITLE
@MybatisTest doesn't load schema.sql automatically

### ISSUE THREAD

**Issue by fishautumn** [mybatis/spring-boot-starter#681]
with annotation `@JdbcTest`, `@DataJdbcTest` and `@DataJpaTest`, schema.sql in classpath are automatically loaded for H2 database.
However it's not for `@MybatisTest`.

The reason is `@MybatisTest` doesn't import DataSourceAutoConfiguration and SqlInitializationAutoConfiguration.

I suggest to add `@AutoConfigureJdbc` to `MybatisTest` to support it.

look at https://github.com/baomidou/mybatis-plus/pull/4625/files#diff-d82d9c2d65aa1489bdfe0d181f41f25f7a9e520bd0b158e462a507b092bb91ed  a reference modification

**Comment by kazuki43zoo** [comment]
@fishautumn 

Cloud you provide reproduce project via GitHub?
I think `DataSourceAutoConfiguration` and `SqlInitializationAutoConfiguration` imports via https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-test-autoconfigure/src/main/resources/META-INF/spring.factories (for Spring Boot 2.x) and https://github.com/mybatis/spring-boot-starter/blob/master/mybatis-spring-boot-test-autoconfigure/src/main/resources/META-INF/spring/org.mybatis.spring.boot.test.autoconfigure.AutoConfigureMybatis.imports (for Spring Boot 3.x).

**Comment by kazuki43zoo** [comment]
@fishautumn 

Probably, this problem belong only MyBatis Plus. MyBatis Plus no applied the `SqlInitializationAutoConfiguration` when update Spring Boot 2.5 based.

FYI: 
We applied the `SqlInitializationAutoConfiguration` when update to Spring Boot 2.5 in this project as follow:
https://github.com/mybatis/spring-boot-starter/commit/73b700cab6c294ebab713397d197757471ab84f1#diff-808fb81708674d5b8c5a8f6aad561ce77feb415e8dae6c13e3cc3774e1c50688

**Comment by fishautumn** [comment]
Thanks @kazuki43zoo for pointing out it.

I will discuss with MyBatis Plus project for that.
