### ISSUE TITLE
Latest spring-framework removed NestedIOException cause ClassNotFoundException

### ISSUE THREAD

**Issue by SunGungg** [mybatis/spring-boot-starter#691]
please remove  org.springframework.core.**NestedIOException** dependency 
![image](https://user-images.githubusercontent.com/19319333/182286580-329a7810-f460-4abf-a57e-e8c1ae954ad2.png)

![image](https://user-images.githubusercontent.com/19319333/182285480-4dd4b9a2-c691-4532-a976-c3dbe3839c1a.png)
![image](https://user-images.githubusercontent.com/19319333/182286707-7e420652-5a9e-4089-ba12-449ef04fe302.png)

We waited for almost half a year
thx~ 
:)

**Comment by SunGungg** [comment]
btw.
My current solution is copy NestedIOException from old spring-core.jar into new jar

**Comment by kazuki43zoo** [comment]
We will support spring boot 3 (spring-framework 6) on 2.3.0 (now only release snapshot version to Sonatype OSS repository). Please use mybatis-spring-boot 2.3.0-SNAPSHOT.
