### ISSUE TITLE
Why mybatis default ExecutorType is Simple not Batch

### ISSUE THREAD

**Issue by homeguess** [mybatis/spring-boot-starter#722]
Why mybatis default ExecutorType is Simple not Batch ? Batch is more effective than Simple . Why use Simple as default ExecutorType ?

**Comment by harawata** [comment]
Hello @homeguess ,

I'm not sure what you mean by 'effective', but SIMPLE is appropriate for the default because it does not do anything unnecessary for simple usages.
If BATCH matches your needs better, you can set `defaultExecutorType` in the config.

**Comment by homeguess** [comment]
> appropriate

Let me  clarify 'effective' mean . If the business usually insert or update 2 tables or 2 rows in one times. I think use BATCH is more effective than SIMPLE . 
Example : SQL :
 insert into table_a (id) values (1);
 insert into table_b (id) values (2);
 insert into table_c (id) values (3);
If use SIMPLE . It will flush these sql 3 times . If use BATCH . It will flush these sql 1 times . 
By the way . If I use @Transactional to the business service . Now I'm using SIMPLE . If I execute SQL above. It will flush these sql just 1times because I use @Tranactional . Right ? If so . What's different with BATCH ?
