### ISSUE TITLE
@Mapper And @MapperScan can not both invalid for springboot IOC

### ISSUE THREAD

**Issue by leavestyle-coder** [mybatis/spring-boot-starter#729]
When I have some mappers with @Mapper such as **UserExtMapper**，and some without @Mapper from jar denpendency such as **UserConfigMapper**.
package: com.nio.user.job.config;
```
@Mapper
public interface UserExtMapper {
    @Select("SELECT * FROM user_account_info WHERE id = ${id}")
    UserAccountInfo selectOne(Long id);
}
```
package: com.nio.user.job.mapper;
```
public interface UserConfigMapper {
    @Select("SELECT * FROM user_account_info WHERE id = ${id}")
    UserAccountInfo selectOne(Long id);
}
```

I use @MapperScan to scan those mapper without @Mapper, then errors happen. 

```
@SpringBootTest
@MapperScan("com.nio.user.job.mapper")
class MapperTest {
    @Autowired
    private UserExtMapper userExtMapper;

    @Autowired
    private UserConfigMapper userConfigMapper;

    @Test
    void test() {
        var user1 = userExtMapper.selectOne(1309870L);
        var user2 = userConfigMapper.selectOne(1309870L);
    }
}
```

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.nio.user.job.MapperTest': Unsatisfied dependency expressed through field 'userConfigMapper'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.nio.user.job.config.UserConfigMapper' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)

I must config @MapperScan for these mappers with @Mapper.

such as:
```
@MapperScan({"com.nio.user.job.mapper", "com.nio.user.job.config"})
```

So, why @Mapper and @MapperScan can not both invalid for springboot IOC.

**Comment by leavestyle-coder** [comment]
dependencies:
```
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis</artifactId>
    <version>3.5.11</version>
</dependency>
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-spring</artifactId>
    <version>2.0.7</version>
</dependency>
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>2.2.2</version>
</dependency>
```

spring-boot version 2.7.5

**Comment by kazuki43zoo** [comment]
Hi @leavestyle-coder, This behavior is specification on this library. As default, this library scan interfaces annotated with `@Mapper` under package of class annotated with `@SpringBootApplication`. But If define the `@MapperScan` in your configuration class, default scanning feature is invalid.
