### ISSUE TITLE
Compile with -parameters option on 3.x

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#737]
Since the Spring 6 has been deprecated to use debug information and it will drop since Spring 6.1. Therefore, we need to compile with -parameters option for library user.

**Comment by hazendaz** [comment]
There is a direct argument for parameters that probably should be used instead.  Also need to add this to our parent pom.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
I've added the parameter to the parent now.
