### ISSUE TITLE
Doesn't spring boot 3.0.0 work normally?

### ISSUE THREAD

**Issue by R3ALW1NNER** [mybatis/spring-boot-starter#748]
Hello,

Spring Boot 3.0.0 is using org.mybatis.spring.boot:mybatis-spring-boot-starter:2.2.2.

language: kotlin 1.7.21

The error was identified during the migration.

Error Message
```
Description:

Parameter 0 of constructor in com.example.demo.Service required a bean of type 'com.example.demo.Mapper' that could not be found.


Action:

Consider defining a bean of type 'com.example.demo.Mapper' in your configuration.

```

Mapper
```kotlin
@Mapper
interface Mapper {

    @Select(
        """
            select 1 from dual
        """
    )
    fun selectTest(): Int
}
```

Service
```kotlin
@Service
class Service(
    private val mapper: Mapper
) {
    fun findTest() = mapper.selectTest()
}
```

**Comment by livk-cloud** [comment]
> The springboot3 automatic assembly method has changed,You need to manually add the autowire file
> Copy `META-INF` to your project's `resources`
https://github.com/livk-cloud/spring-boot-example/tree/main/spring-mybatis/mybatis-example/src/main/resources

**Comment by R3ALW1NNER** [comment]
@kazuki43zoo Thank you for your kind quick reply.

I'll be waiting for the new version to be released.

**Comment by R3ALW1NNER** [comment]
I will close the issue by updating to 3.0.0.
