### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by kevin19891229** [mybatis/spring-boot-starter#76]
In file "spring-boot-starter/mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml/src/main/resources/sample/mybatis/mapper/CityMapper.xml", I found "<mapper namespace="sample.mybatis.mapper.CityMapper">" and it works.
What's the rule of namespace?

**Comment by emacarron** [comment]
The rule of thumb is: the namespace should be equal to the mapper name. 

So, that empty namespace is an error, though it is too late for us to add a validation for that because we may break existing code.

**Comment by kevin19891229** [comment]
Thanks, I made a mistake. I mean I found "mapper namespace="sample.mybatis.mapper.CityMapper"
", but the file CityMapper does not exist in the current module. I think CityDao may be the related one, but when I change CityMapper to CityDao, it does not work.

**Comment by emacarron** [comment]
Having a Mapper interface is optional. You may use the xml directly instead. The CityDao is not a mapper but a "classic" Dao that uses the MyBatis API to execute statements written in the xml file.
