### ISSUE TITLE
"mybatis-spring-boot-autoconfigure" Web page: Link error

### ISSUE THREAD

**Issue by chenjiee815** [mybatis/spring-boot-starter#77]
URL: http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Running_Samples

The link of '2nd Sample' should be https://github.com/mybatis/spring-boot-starter/tree/master/mybatis-spring-boot-samples/mybatis-spring-boot-sample-xml .

**Comment by emacarron** [comment]
Fixed. Thank you!
