### ISSUE TITLE
After executing the new sql, the object id is changed

### ISSUE THREAD

**Issue by Keafmd** [mybatis/spring-boot-starter#794]
After executing the new sql, the object id is changed.
Why? Does this happen occasionally?

**Comment by Keafmd** [comment]
```java
ptListMapper.insertPtList(ptList);
//It needs to be reset, otherwise the ID is incorrect
ptList.setId(ptListId);
return ptList;
```

**Comment by Keafmd** [comment]
mybatis.spring.boot.starter.version>1.3.2

**Comment by harawata** [comment]
Hello @Keafmd ,

It probably means that the value of `id` is auto-generated by the DB (i.e. `AUTO_INCREMENT`, `IDENTITY`, etc.) and MyBatis' `useGeneratedKeys` is enabled globally or for the statement.
https://github.com/mybatis/mybatis-3/wiki/FAQ#how-can-i-retrieve-the-value-of-an-auto-generated-key
https://mybatis.org/mybatis-3/configuration.html#settings

Note that MyBatis-Spring-Boot-Starter 1.3.2 is EOL (=no longer supported).
Please use a newer version.
http://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/

**Comment by Keafmd** [comment]
As you said, I did make relevant configuration. Thank you!
