### ISSUE TITLE
how to add a mybatis plugin use annotation?

### ISSUE THREAD

**Issue by linzebin** [mybatis/spring-boot-starter#80]
how to add a mybatis plugin use annotation?

**Comment by zhxxcq** [comment]
I use this configuration for mybatis plugin and that work ok.
`@Configuration
@AutoConfigureAfter(MybatisAutoConfiguration.class)
public class MybatisPageHelperInterceptor {

    @Bean
    @ConditionalOnMissingBean
    public PageHelper pageHelperInterceptor() {
        PageHelper pageHelper = new PageHelper();
        Properties properties = new Properties();
        properties.setProperty("reasonable", "true");
        properties.setProperty("supportMethodsArguments", "true");
        properties.setProperty("returnPageInfo", "check");
        properties.setProperty("params", "count=countSql");
        pageHelper.setProperties(properties);

        return pageHelper;
    }

}`
and spring boot will take this and mybatis can detect this plugin.
Hope you have to help.

**Comment by linzebin** [comment]
It worked : )
