### ISSUE TITLE
Upgrade to spring-boot 1.4.0

### ISSUE THREAD

**Issue by eddumelendez** [mybatis/spring-boot-starter#85]

**Comment by kazuki43zoo** [comment]
👍

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez 

Milestone is 1.1.2(maintenance version up) ? I think 1.2.0(minor version up) is better. What do you think ?

**Comment by eddumelendez** [comment]
@kazuki43zoo you read my mind. I will review son pending PRs and then tell the team to release with version `1.2.0`
