### ISSUE TITLE
Result map to HashMap sometime response hex value

### ISSUE THREAD

**Issue by frankchenpeng** [mybatis/spring-boot-starter#870]
I have mapper defines a query which receives a string as parameter and List of map as requery result.
`@MapKey("ipAddress")`
 `List<Map<String, String>> queryCertificate(@Param("id")String id);
` 

The select sql in mapper.xml as blow

`SELECT sv.host_ip as "ipAddress", cert.common_name as "commonName"`
        `FROM server as sv inner join certificate as cert on cert.server_id = sv.server_id`
        `WHERE ..............`

Normally the response of the query is correct with actually value in database

```
----------------------------------------------
| ipAddress        | 10.192.86.107 |
| commonName|  test.com.cn    |
---------------------------------------------
| ipAddress        | 10.192.86.105 |
| commonName|  test.com.cn    |
```
but when the query happens in a loop, after serveral times query the result show as hex vaule of actuall value in database.
```
----------------------------------------------
| ipAddress        |  0ac0566b                               |
| commonName|  A385A2A34B8396944B8395  |
---------------------------------------------
| ipAddress        |  0ac05669                               |
| commonName| A385A2A34B8396944B8395   |

```

Artifact Version：2.2.2
Database： PostgreSQL 12
I don't know why this happen and how to fix it if I still want to map the query result to List of HashMap

**Comment by recaton** [comment]
If you use queries in loops, you should consider mybatis caching.

You can check your business logic to see if the result map has been modified between two iterations.

for example:
```java
for (int i = 0; i < 10; i++) {
  List<Map<String, String>> result = mapper.queryFromDB();
  // The value of result will change every iteration
  System.out.ptintln(result);
  result.get(0).put("A", "B" + i);
}
```

**Comment by frankchenpeng** [comment]
@recaton thank you for your great reminding, the hit the root cause, we need to rebuild the query result each time when perform the query instead of  use the return object in mapper. will close the issue.
