### ISSUE TITLE
Could not open ServletContext resource [/mybatis-config.xml]

### ISSUE THREAD

**Issue by 928255095** [mybatis/spring-boot-starter#88]
application.properties
# mybatis config
spring.datasource.schema=import.sql
mybatis.config-location=mybatis-config.xml
logging.level.root=WARN
logging.level.sample.mybatis.mapper=TRACE

and mybatis-config.xml same catalog application.properties

**Comment by 928255095** [comment]
oh I know
 mybatis.config-location=classpath:/mybatis-config.xml

**Comment by eddumelendez** [comment]
If it has been solved, can you close the issue?
