### ISSUE TITLE
Why my spring-boot-starter use yml configuration file instead of .properties

### ISSUE THREAD

**Issue by kopax** [mybatis/spring-boot-starter#89]
I am using the same versions as in [PR79](https://github.com/mybatis/spring-boot-starter/pull/79)

I have followed this tutorial to initialize my Spring project : https://spring.io/guides/gs/spring-boot-docker/

I don't understand why the configuration files use .properties, while mine use .yml.

**Comment by eddumelendez** [comment]
@kopax I don't understand your question. Is it related to mybatis-spring-boot-starter?
