### ISSUE TITLE
Switch baseline to Spring Boot 3.2.x

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#895]
We change baseline to Spring Boot 3.2.x after releasing Spring Boot 3.2 GA version.

* Spring Framework 6.1
* Spring Batch 5.1

**Comment by namero999** [comment]
Will this also mean that we'll get more frequent updates of the spring boot starter? Usually the boot starter lags behind the releases of the standalone mybatis library. It would be great to have a release sync.

**Comment by hazendaz** [comment]
Hi, sorry we are a small team so it's hard for us to be entirely in sync on our repos.  However, we are working hard to change that in near future through more automated and easier release process.  Hope is we will get to point of releasing when mybatis core or spring boot releases so compatibility is much more clear to our users.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by namero999** [comment]
No need to be sorry, you are doing an amazing work, and mybatis is still a pleasure to work with after all these years!

Do you need any help with these things? I can't guarantee I'm up to the task, but I realize it's time to give back to mybatis in one way or another :)

**Comment by hazendaz** [comment]
I'd say we probably need help with users reviewing code in general and fixing up anything deprecated and what not.  Feels like there is always something to do that can keep us busy for sure.

**Comment by kazuki43zoo** [comment]
Fixed via #918
