### ISSUE TITLE
Support JDK 22 on CI

### ISSUE THREAD

**Issue by kazuki43zoo** [mybatis/spring-boot-starter#904]
We need to update as following libraries.

* [Jacoco 0.8.11+](https://www.jacoco.org/jacoco/trunk/doc/changes.html)
* [Groovy 4.0.16+](https://issues.apache.org/jira/browse/GROOVY-11197)

**Comment by hazendaz** [comment]
jacoco applied via parent now.  Just waiting on groovy.

**Comment by kazuki43zoo** [comment]
Close because already supported.
