### ISSUE TITLE
how can i integration spring boot mybatis with pagehelper

### ISSUE THREAD

**Issue by chengbaobao630** [mybatis/spring-boot-starter#91]
when i use pagehelper  and annotation Sqlprovider 

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'providerTakesParameterObject' in 'class org.apache.ibatis.builder.annotation.ProviderSqlSource'

i find field providerTakesParameterObject in class PageProviderSqlSource ,but not in  use

**Comment by mallim** [comment]
Just upgrade your pagehelper version, refer to http://git.oschina.net/free/Mybatis_PageHelper/issues/102 for more details

**Comment by chengbaobao630** [comment]
thanks
