### ISSUE TITLE
When is the 3.0.3 release scheduled?

### ISSUE THREAD

**Issue by yu-shiba** [mybatis/spring-boot-starter#919]
Spring Boot 3.2 has been released, but projects that depend on `org.mybatis.spring.boot:mybatis-spring-boot-starter` fail to start due to a problem with mybatis/spring#855.

When is the `3.0.3` release of `mybatis-spring-boot-starter` scheduled?

**Comment by kazuki43zoo** [comment]
@yu-shiba We release as soon as possible. Please wait just a moment.

**Comment by kazuki43zoo** [comment]
We already released!

**Comment by yu-shiba** [comment]
@kazuki43zoo Thank you for your prompt response.
