### ISSUE TITLE
Enable properties via application.properties

### ISSUE THREAD

**Issue by tokuhirom** [mybatis/spring-boot-starter#94]
I'm putting few configurations in mybatis.xml.
I want to configure mybatis in application.properties instead.

I'm using mybatis.xml like following. I wonder if I can configure it in application.properties.

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>
    <settings>
        <setting name="mapUnderscoreToCamelCase" value="true"/>
        <setting name="defaultFetchSize" value="100"/>
        <setting name="defaultStatementTimeout" value="30"/>
        <!-- Throw exception when auto property mapping failed -->
        <setting name="autoMappingUnknownColumnBehavior" value="FAILING"/>
    </settings>
</configuration>
```

**Comment by kazuki43zoo** [comment]
Hi @tokuhirom, you can configure above configurations via `application.properties` since 1.1.0.

```properties
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=true
mybatis.configuration.auto-mapping-unknown-column-behavior= FAILING
```

But these properties cannot use at the same time with the `mybatis.config-location` property.

http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/#Configuration

**Comment by tokuhirom** [comment]
Oh! I don't know about this type of configuration properties. Thanks!
