### ISSUE TITLE
Incompatible type between Configuration SqlSessionFactoryBean and MybatisProperties

### ISSUE THREAD

**Issue by szopal** [mybatis/spring-boot-starter#959]
After upgrade mybatis version to 3.0.3 I can't customize SqlSessionFactory because I can't set mybatis properties configuration like I did in 2.3.1

```
@Bean
@ConfigurationProperties(prefix = MybatisProperties.MYBATIS_PREFIX)
public SqlSessionFactory sqlSessionFactoryBean(final MybatisProperties properties) throws Exception {
  final SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
  [...here is some of my code...]
  factoryBean.setConfiguration(properties.getConfiguration());
  return factoryBean.getObject();
}
```

There is error:

![image](https://github.com/mybatis/mybatis-3/assets/57896357/56dd4ca8-6f48-4161-8349-fa51b991e0b4)

**Comment by harawata** [comment]
Hello @szopal ,

I moved the issue to mybais-spring-boot-starter repo.

See if [ConfigurationCustomizer](https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/index.html#using-a-configurationcustomizer) or [SqlSessionFactoryBeanCustomizer](https://mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/index.html#using-a-sqlsessionfactorybeancustomizer) helps.

There also seems to be a case that is not covered currently. See #928 .

If none of the above helps, please elaborate on the usage details.

**Comment by szopal** [comment]
Thank very much! Now I can see it's changed in 3.0.

**Comment by hazendaz** [comment]
closing issue as seems resolved.
