### ISSUE TITLE
why maven can't find 1.2.0

### ISSUE THREAD

**Issue by mrvon2015** [mybatis/spring-boot-starter#97]
why maven can't find 1.2.0

**Comment by kazuki43zoo** [comment]
1.2.0 has not been released yet.

**Comment by kazuki43zoo** [comment]
If you use a snapshot version(1.2.0-SNAPSHOT), please add maven repository settings as follows:

```xml
<repository>
  <id>sonatype-oss-snapshots</id>
  <name>Sonatype OSS Snapshots Repository</name>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</repository>
```

**Comment by mrvon2015** [comment]
thanks

**Comment by eddumelendez** [comment]
@mrvon2015 every snapshot is published after each commit. As a @kazuki43zoo said you need the snapshot repository to be added in your `pom.xml`.
