### ISSUE TITLE
MyBatis Cache Per Request: Should Be Cleared When a Request Ends

### ISSUE THREAD

**Issue by ghenmelo** [mybatis/spring-boot-starter#983]
Good evening,

I would like to inquire if there is a way to enable read-only cache per request in MyBatis. The idea is that a select statement, with the same parameters, should return the same result for any query within the context of that request, without the need for manual control.

It would be very useful if this could be achieved through configuration alone, without the need to implement additional logic in the code. This would allow for performance optimization of read-only operations, ensuring that the cache is cleared at the end of each request, preventing stale or inconsistent data.

Thank you in advance for your attention and suggestions.

Best regards,

Guilherme Melo.

**Comment by harawata** [comment]
Hello @ghenmelo ,

By default, if you call the same select statement with the same parameters within the same session, the result will be retrieved from the [local cache](https://mybatis.org/mybatis-3/java-api.html#local-cache).

**Comment by ghenmelo** [comment]
Hello @harawata , thank you for your attention.

In my case, it is not working as expected. I made several sequential calls to the database and used a UUID in the database to confirm. The return continues to be different for each call. However, when I used <cache/> in my XML for second-level (global) caching, it did work. But my case is a bit more specific.

Even though the local cache did not seem to work for me, the local cache is by session, which means a database session, correct? So, it would be the same session for multiple simultaneous requests? What I am looking for is for each request to generate a new cache that will be cleared when the request ends. I`m using java 11 with Mybatis 2.3.

**Comment by harawata** [comment]
I should have been clearer.
When talking about MyBatis, "session" means SqlSession.
https://mybatis.org/mybatis-3/getting-started.html#sqlsession

As you use mybatis-spring-boot, transactions may be managed by Spring and one SqlSession is created and used for each transaction.
https://mybatis.org/spring/transactions.html
So, you basically need to execute the SELECTs in the same transaction.

If you still have difficulty, please create a simplified demo project and share it on your GitHub repo.
Here are some templates and examples: https://github.com/harawata/mybatis-issues

**Comment by ghenmelo** [comment]
@harawata Hi again !!

I found what was causing my issues. It was due to the use of parallelStream() in my loop. When I changed it to stream(), the first-level cache worked as expected. Is there any configuration to make or a way to work around this problem?

see ya.

**Comment by harawata** [comment]
@ghenmelo ,

It sounds like you are using `parallelStream()` against something that is not thread-safe.
If that is the case, it is not a problem that can be worked around by changing configuration.

I'll close this as it sounds like a case of misuse.
If you believe there is a bug, please provide the demo project and we will reopen.
